Translation of the "Fragment" page
reactjs/fr.react.dev pull request #455
Opened 2023-04-26 12:16 UTC by bastiendmt

Hello, voici ma PR pour la traduction de la page "Fragment", j'espère que c'est ok, ouverte aux retours 😀

2023-04-26 12:19 UTC, bastiendmt commented on src/content/reference/react/Fragment.md
> +`<Fragment>`, souvent utilisé avec la syntaxe `<>...</>`, vous permet de grouper des éléments sans balise englobante.
Pas sur de devoir traduire "wrapper node", ni c'est si la traduction la plus adaptée

2023-04-26 12:19 UTC, bastiendmt commented on src/content/reference/react/Fragment.md
> +Les Fragments sont utiles car grouper des éléments avec un Fragment n'as pas d'effet sur la mise en page ou les styles, contrairement à l'utilisation d'un autre balise englobante du DOM. Si vous insp
Pas sur de la traduction de `siblings` => `enfants` ?

2023-04-27 08:23 UTC, tdd requested changes
Salut @bastiendmt !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +- **optionnel** `key`: Les Fragments déclarés explicitement avec la syntaxe `<Fragment>` peuvent contenir des [keys.](/learn/rendering-lists#keeping-list-items-in-order-with-key)
```suggestion
- `key` **optionnel** : les fragments déclarés explicitement avec la syntaxe `<Fragment>` peuvent avoir une [keys](/learn/rendering-lists#keeping-list-items-in-order-with-key).
```

- Tu as perdu de vue l'ordre français des mots 😁 Ici l'adjectif serait en position attribut, donc après.
- Espaces insécables devant les signes de ponctuation doubles.
- Pas de majuscules en français après un deux-points.
- "have", pas "contain", comme on parle de props ici, donc "avoir".
- La VO n'est pas claire mais un élément React a au maximum une `key`.
- En anglais, les règles de ponctuation font que le plus souvent, une ponctuation à la fin d'un groupe (par exemple paire de guillemets, ou sur le web hyperlien) est *au sein* du groupe, comme dans ces docs les points finaux toujours au sein des liens. En français non, on sort donc le point pour le mettre après le lien.

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +- Si vous souhaitez utiliser des `key` dans un Fragment, vous ne pouvez pas utiliser la syntaxe `<>...</>`. Vous devez explicitement importer `Fragment` depuis `'react'` et rendre `<Fragment key={you
```suggestion
- Si vous souhaitez utiliser une `key` dans un Fragment, vous ne pouvez pas utiliser la syntaxe `<>...</>`. Vous devez explicitement importer `Fragment` depuis `'react'` et écrire `<Fragment key={yourKey}>...</Fragment>`.
```

Comme l'indiquent les BP de trad, on évite au maximum d'utiliser "rendre" comme verbe. Chaque fois que le distingo n'est pas critique, on utilisera selon le contexte "afficher", "renvoyer" ou "écrire" (ici on parle de la syntaxe à employer). Si vraiment on parle de la notion technique React de *rendering*, on dira plutôt "faire le rendu" ou "faire son rendu" si le sujet est le composant qui fait le rendu.

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +- React ne [réinitialise pas l'état](/learn/preserving-and-resetting-state) quand vous passez de rendre `<><Child /></>` à `[<Child />]` et inversement, ou ni si vous passez de rendre `<><Child /></>
```suggestion
- React ne [réinitialise pas l'état](/learn/preserving-and-resetting-state) quand vous passez d'une structure `<><Child /></>` à `[<Child />]` et inversement, ni quand vous passez de `<><Child /></>` à `<Child />` et inversement. Ça ne marche qu’à un niveau de profondeur : par exemple, passer de `<><><Child /></></>` à `<Child />` réinitialise l'état. Consultez [la sémantique précise ici](https://gist.github.com/clemmy/b3ef00f9507909429d8aa0d3ee4f986b).
```

- Quelques écarts de sens ("plus profond")
- "Rendre", etc.
- On évite d'utiliser des subordonnées basées sur un infinitif, on va simplifier autant que possible.
- Amélioration de l'accessibilité du lien en évitant juste "ici" comme texte (souci de la VO aussi).

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +Utilisez `Fragment`, ou la syntaxe équivalente `<>...</>`, afin de grouper plusieurs éléments ensemble. Vous pouvez l'utiliser pour mettre plusieurs éléments à la place d'un élément. Par exemple, un
```suggestion
Utilisez `Fragment`, ou la syntaxe équivalente `<>...</>`, afin de grouper plusieurs éléments ensemble. Vous pouvez l'utiliser pour passer plusieurs éléments là où un seul est attendu. Par exemple, un composant ne peut renvoyer qu'un seul élément, mais avec un Fragment vous pouvez grouper plusieurs éléments et renvoyer ce groupe :
```

- Clarification du cas d'usage

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +Les Fragments sont utiles car grouper des éléments avec un Fragment n'as pas d'effet sur la mise en page ou les styles, contrairement à l'utilisation d'un autre balise englobante du DOM. Si vous insp
En effet, ce n'est pas ça ("children"). "Siblings" n'a hélas pas de traduction satisfaisante en un mot, ça désigne les frères et sœurs IRL, donc les éléments de même parent en fait.

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +Les Fragments sont utiles car grouper des éléments avec un Fragment n'as pas d'effet sur la mise en page ou les styles, contrairement à l'utilisation d'un autre balise englobante du DOM. Si vous insp
```suggestion
Les Fragments sont utiles car grouper des éléments avec un Fragment n'as pas d'effet sur la mise en page ou les styles, contrairement à l'enrobage par une balise conteneur telle qu’un élément DOM. Si vous inspectez cet exemple avec les outils du navigateur, vous verrez que toutes les balises `<h1>` et `<p>` du DOM apparaissent au même niveau (avec le même parent), sans balise enrobante :
```

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +      <Post title="Une mise à jour" body="Ça fait un moment que je n'ai pas posté..." />
```suggestion
      <Post title="Des nouvelles" body="Ça fait un moment que je n’ai pas écrit..." />
```

Soyons le plus idiomatiques possible vu le contexte sémantique 😄

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +L'exemple ci-dessus est equivalent à importer `Fragment` depuis React :
```suggestion
L'exemple ci-dessus revient à importer `Fragment` depuis React :
```

"est équivalent à" + infinitif, c'est ampoulé.

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +Normalement vous n'aurez pas besoin d'utiliser ça à moins d'avoir besoin de [donner des `key` à votre `Fragment`.](#rendering-a-list-of-fragments)
```suggestion
Normalement vous n'aurez pas besoin d'utiliser ça à moins de vouloir [associer une `key` à votre `Fragment`](#rendering-a-list-of-fragments).
```

- Double "avoir besoin" reformulé
- Point hors du lien

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +### Initialiser plusieurs éléments à une variable {/*assigning-multiple-elements-to-a-variable*/}
```suggestion
### Affecter plusieurs éléments à une variable {/*assigning-multiple-elements-to-a-variable*/}
```

"Assign" ne signifie pas "Initialiser" ?!

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +Comme pour tous les autres éléments, vous pouvez initialiser un Fragment à des variables, les passer en tant que props, etc :
```suggestion
Comme pour tous les autres éléments, vous pouvez affecter des Fragment à des variables, les passer en tant que props, etc. :
```

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +      Êtes vous sûr de vouloir quittez cette page ?
```suggestion
      Êtes vous sûr·e de vouloir quitter cette page ?
```

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +### Englober des éléments avec du texte {/*grouping-elements-with-text*/}
```suggestion
### Grouper des éléments et du texte {/*grouping-elements-with-text*/}
```

Écart de sens.

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +Vous pouvez utilisez `Fragment` pour grouper des textes avec des éléments :
```suggestion
Vous pouvez utiliser `Fragment` pour grouper du texte et des éléments :
```

Un peu de fatigue sur les accords et infinitifs 😉

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +### Rendre une liste de Fragments {/*rendering-a-list-of-fragments*/}
```suggestion
### Afficher une liste de Fragments {/*rendering-a-list-of-fragments*/}
```

La distinction n'est pas importante ici, on peut dire "afficher".

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +Voici une situation ou vous avez besoin d'écrire explicitement `Fragment` plutôt que d'utiliser la syntaxe `<></>`. Quand vous [rendez plusieurs éléments dans une boucle](/learn/rendering-lists), vou
```suggestion
Voici un cas de figure où vous devez écrire `Fragment` explicitement plutôt que d'utiliser la syntaxe `<></>`. Quand vous [affichez plusieurs éléments dans une boucle](/learn/rendering-lists), vous avez besoin d'associer une `key` à chaque élément. Si les éléments compris dans la boucle sont des Fragments, vous devez utiliser la syntaxe classique JSX afin de fournir la prop `key` :
```

La VO n'est pas parfaite… Elle utilise "the" au lieu de "some" (le truc reste vrai pour tout fragment dans la liste, même si le reste est constitué d'éléments classique), et elle entretient la confusion (pas mal présente dans les nouvelles docs) entre "prop" et "attribut". Je tends à vouloir préserver le distingo historique qui réserve "attribut" aux éléments natifs et "prop" à ce qui touche à React, **surtout** pour les props techniques que sont `key`, `ref` et `children`.

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +Vous pouvez inspecter le DOM pour vérifier qu'il n'y a pas de balise englobante autour des enfants du Fragment :
```suggestion
Vous pouvez inspecter le DOM pour vérifier qu'il n'y a pas d'élément enrobant autour des enfants du Fragment :
```

"Balise" est un terme de syntaxe. Le DOM ne contient pas de balise, que des nœuds (essentiellement texte et éléments). `#ayatollah`

2023-04-27 08:23 UTC, tdd commented on src/content/reference/react/Fragment.md
> +  { id: 1, title: 'Une mise à jour', body: "Ça fait un moment que je n'ai pas posté..." },
```suggestion
  { id: 1, title: 'Des nouvelles', body: "Ça fait un moment que je n'ai pas écrit..." },
```

Cohérence avec la correction d'avant.

2023-04-27 11:10 UTC, tdd approved these changes

2023-04-27 11:12 UTC, merged

2023-04-27 11:42 UTC, bastiendmt commented
Bizarrement je n'avais tous les changes dans l'onglet files 🫤 j'ai appliqué les corrections à la main mais en plusieurs commit du coup

2023-04-27 12:16 UTC, tdd commented
@bastiendmt ah oui super bizarre… Normalement tout marche. En tous les cas j'avais bien toutes tes prises en compte, j'ai donc mergé. J'ai fait une dernière repasse directement sur `main` car j'avais oublié la repasse visuelle (pas d'orphelins, etc.) et typo (apostrophes, guillemets, insécables) sur ta branche.

Bravo pour ta première trad intégrée en tout cas ! 👏👏👏

https://fr.react.dev/reference/react/Fragment