Traduction of the "Reacting to input with state" page
reactjs/fr.react.dev pull request #461
Opened 2023-04-27 20:57 UTC by KohdeAvekLeQ

Voilà ma PR pour cette nouvelle page, j'ai tenu compte des remarques de la précédente, il devrait y avoir moins d'erreurs, merci pour vos reviews.

2023-04-27 20:58 UTC, KohdeAvekLeQ commented on src/content/learn/reacting-to-input-with-state.md
> +Les pages de ce type sont souvent appelées "living styleguides" ou "storybooks"
Ici je savais pas vraiment comment traduire ou ne pas traduire

2023-04-27 20:59 UTC, KohdeAvekLeQ commented on src/content/learn/reacting-to-input-with-state.md
>      <b id="lastNameText">Jacobs</b>
Je n'ai pas eu d'idée pour le nom de famille "francisé", ou si je laisse comme ça

2023-04-28 08:48 UTC, tdd commented
@KohdeAvekLeQ quand tu es prêt à la review, dis-le en sortant du mode Draft. Si tu crées ta PR prête d'entrée de jeu, crée-la en mode normal, pas en draft, ok ?

je la repasse en "ready for review", là.

2023-04-28 08:50 UTC, tdd commented
(Ah et aussi : tes titres de PR devraient choisir leur langue : "Traduction of the page" c'est mixé 😉).

Tu peux tout à fait utiliser un titre 100% français "Traduction de la page…" sinon 100% anglais "*Translation* of the… page"

2023-04-28 08:55 UTC, KohdeAvekLeQ commented
Oops effectivement, traduction est pas trop anglais, ok pour le type de PR

2023-04-28 10:43 UTC, tdd requested changes
Salut @KohdeAvekLeQ !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de continuer à nous filer un coup de main.

On sent que ça s'améliore, j'ai vu en effet la prise en compte de pas mal de retours de ta première trad. Évidemment, tout n'est pas parfait, certaines "erreurs" sont toujours bien là, mais c'est normal, c'est le process ! 😁 

**J'ai fait la review jusqu'aux Défis**, mais pas encore les Défis. Je suis pris cet après-midi, mais je voulais te donner de quoi avancer sans attendre longtemps (car je vais être en congés jusqu'à la Pentecôte).

Avec un peu de bol je pourrai trouver le temps de finaliser ma review avant de partir.

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-04-28 10:43 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Vous souhaitez éviter les doublons dans le contenu des états afin de ne suivre que ce qui est essentiel. En consacrant un peu de temps à la refonte de votre structure d’état, vous rendrez vos composa
```suggestion
Il est préférable d’éviter les doublons entre éléments ɗ’état afin de se concentrer sur ce qui est essentiel. En consacrant un peu de temps à la refonte de votre structure d’état, vous rendrez vos composants plus faciles à comprendre, vous réduirez la duplication et vous éviterez des erreurs d’interprétation. Votre objectif est d’**éviter les cas où l’état en mémoire ne représente aucune interface valide que vous accepteriez de montrer à l’utilisateur**. (Par exemple, vous ne voulez jamais afficher un message d’erreur et désactiver la saisie en même temps, ou l’utilisateur ne sera pas en mesure de corriger l’erreur !)
```

2023-04-28 10:43 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Voici quelques questions que vous pouvez poser sur vos variables d'état :
```suggestion
Voici quelques questions que vous pouvez vous poser sur vos variables d'état :
```

2023-04-28 10:43 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +* **Es-ce que cet état cause un paradoxe ?** Par exemple, `isTyping` et `isSubmitting` ne peuvent pas être tous les deux définis à `true`. Un paradoxe signifie généralement que l’état n’est pas suffi
```suggestion
* **Es-ce que cet état est paradoxal ?** Par exemple, `isTyping` et `isSubmitting` ne peuvent pas être tous les deux à `true`. Un paradoxe signifie généralement que l’état n’est pas suffisamment contraint. Il y a quatre combinaisons possibles de deux booléens, mais seulement trois correspondent à des états valides. Pour supprimer l’état « impossible », vous pouvez les combiner dans un `status` qui doit être l’une des trois valeurs suivantes : `'typing'`, `'submitting'`, ou `'success'`.
```

2023-04-28 10:43 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +* **Pouvez-vous obtenir la même information à partir de l’inverse d'une autre variable d’état ?** `isError` n’est pas nécessaire car vous pouvez vérifier `error !== null` à la place.
```suggestion
* **Pouvez-vous obtenir la même information en inversant une autre variable d’état ?** `isError` n’est pas nécessaire car vous pouvez vérifier `error !== null` à la place.
```

2023-04-28 10:43 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +### Étape 5: Connecter les gestionnaires d’évènements pour définir l’état {/*step-5-connect-the-event-handlers-to-set-state*/}
```suggestion
### Étape 5 : connecter les gestionnaires d’événements pour définir l’état {/*step-5-connect-the-event-handlers-to-set-state*/}
```

2023-04-28 10:43 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +  5. Connecter les gestionnaires d’événements pour définir l’état.
```suggestion
* La programmation déclarative consiste à décrire l’interface utilisateur pour chaque état visuel plutôt que de micro-gérer l’interface (style impératif).
* Lors du développement d’un composant :
  1. Identifiez tous ses états visuels.
  2. Déterminez les déclencheurs humains et techniques des changements d’état.
  3. Modélisez l’état avec `useState`.
  4. Supprimez les états non essentiels pour éviter les bugs et les paradoxes.
  5. Connectez les gestionnaires d’événements pour définir l’état.
```

2023-04-28 13:45 UTC, tdd requested changes
Yay @KohdeAvekLeQ, j'ai pu finir la review !

Je te laisse regarder et appliquer, après quoi je ferai ma repasse finale en local (typographie restante, ajustements "Deroin" manquants, et repasse visuelle pour éliminer les lignes à un seul mot, à coup de reformulations).

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Une seule variable d’état booléenne suffit pour se souvenir si l’image est active. La tâche initiale était de supprimer ou d’ajouter des classes CSS. Cependant, dans React, vous devez *décrire* ce qu
```suggestion
Une seule variable d’état booléenne suffit pour se souvenir si l’image est active. La tâche initiale était de supprimer ou d’ajouter des classes CSS. Avec React cependant, vous devez *décrire* ce que vous voulez voir plutôt que *manipuler* les éléments de l’interface utilisateur. Vous devez donc calculer les deux classes CSS en fonction de l’état actuel. Vous devez également [arrêter la propagation](/learn/responding-to-events#stopping-propagation) pour que le clic sur l’image ne soit pas aussi exploité comme clic sur l’arrière-plan.
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Vérifiez que cette version fonctionne en cliquant sur l’image puis en dehors :
```suggestion
Vérifiez que cette version fonctionne en cliquant sur l’image puis en-dehors :
```

Toujours les tirets manquants sur ce type de CCL… 😉

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Alternativement, vous pouvez retourner deux pièces séparées de JSX :
```suggestion
Autrement, vous pouvez retourner deux morceaux distincts de JSX :
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Gardez à l'esprit que si deux morceaux JSX différents décrivent le même arbre, leur imbrication (première `<div>` → première `<img>`) doit s’aligner. Sinon, basculer `isActive` recréerait tout l'arbr
```suggestion
Gardez à l'esprit que si deux morceaux de JSX différents décrivent le même arbre, leur imbrication (première `<div>` → première `<img>`) doit correspondre. Sinon, basculer `isActive` recréerait tout l'arbre en-dessous et [réinitialiserait son état](/learn/preserving-and-resetting-state). C’est pourquoi, si un arbre JSX similaire est renvoyé dans les deux cas, il est préférable de l’implémenter comme un seul morceau de JSX.
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +#### Éditeur de profil {/*profile-editor*/}
Majuscule accentuée 👍 😉 

J'ai vu que tu sors bien les ponctuations des fins de liens aussi, GG !

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Voici un court questionnaire implémenté en JavaScript pur et le DOM. Utilisez le pour comprendre son comportement :
```suggestion
Voici un court questionnaire implémenté en JavaScript pur avec le DOM. Utilisez-le pour en comprendre le comportement :
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +  <p><i id="helloText">Bonjour, Jeanne Jacobs !</i></p>
```suggestion
  <p><i id="helloText">Bonjour, Jeanne Deroin !</i></p>
```

Du coup…

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Ce questionnaire passe d’un mode à l’autre : en mode édition, vous voyez les entrées, et en mode visualisation, vous ne voyez que le résultat. L’intitulé du bouton change entre « Modifier » et « Enre
```suggestion
Ce questionnaire passe d’un mode à l’autre : en mode édition, vous voyez les champs de saisie, et en mode visualisation, vous ne voyez que le résultat. L’intitulé du bouton bascule entre « Modifier » et « Enregistrer » en fonction du mode dans lequel vous vous trouvez. Lorsque vous modifiez les saisies, le message de bienvenue en bas de page est mis à jour en temps réel.
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Votre tâche consiste à le réimplémenter en React dans le bac à sable ci-dessous. Pour votre commodité, le balisage a déjà été converti en JSX, mais vous devrez faire en sorte qu’il affiche et cache l
```suggestion
Votre tâche consiste à le réimplémenter en React dans le bac à sable ci-dessous. Pour vous aider à démarrer, le balisage a déjà été converti en JSX, mais vous devrez faire en sorte qu’il affiche ou masque les champs de saisie comme le fait l’original.
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +        Prenom :{' '}
```suggestion
        Prénom :{' '}
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +      <p><i>Bonjour, Jeanne Jacobs !</i></p>
```suggestion
      <p><i>Bonjour, Jeanne Deroin !</i></p>
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +        Modifier le Profil
```suggestion
        Modifier le profil
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +Si vous avez du mal à savoir par où commencer, le code ci-dessous a déjà la plupart de la structure en place. Si vous commencez ici, complétez la logique manquante dans la fonction `updateDOM`. (Réfé
```suggestion
Si vous avez du mal à savoir par où commencer, le code ci-dessous a déjà la plupart de la structure en place. Si vous commencez ici, complétez la logique manquante dans la fonction `updateDOM`. (Référez-vous au code original si nécessaire.)
```

Quand une phrase entière est comprise entre parenthèses (la précédente avait déjà son point), le point final est *dans* les parenthèses. Micro-détail de typographie 😉

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +    // A FAIRE : afficher les entrées, cacher le contenu
```suggestion
    // TODO: afficher les champs, cacher le contenu
```

On garde le "TODO" dans le marqueur, comme ailleurs dans les docs VF, notamment parce qu'il est auto-détecté par plein d'outils et d'extensions (ex. Todo Tree sur VS Code, WebStorm, etc.)

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +    // A FAIRE : cacher les entrées, afficher le contenu
```suggestion
    // TODO: masquer les champs, afficher le contenu
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +  // A FAIRE : mettre à jour les textes
```suggestion
  // TODO: mettre à jour les textes
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +  <p><i id="helloText">Bonjour Jeanne Jacobs !</i></p>
```suggestion
  <p><i id="helloText">Bonjour Jeanne Deroin !</i></p>
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +La logique manquante comprenait le basculement de l’affichage des entrées et du contenu, ainsi que la mise à jour des textes :
```suggestion
Les traitements manquants comprenaient le basculement de l’affichage des champs et du contenu, ainsi que la mise à jour des textes :
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +    Prénom:
```suggestion
    Prénom :
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +  <p><i id="helloText">Bonjour, Jeanne Jacobs !</i></p>
```suggestion
  <p><i id="helloText">Bonjour, Jeanne Deroin !</i></p>
```

2023-04-28 13:45 UTC, tdd commented on src/content/learn/reacting-to-input-with-state.md
> +La fonction `updateDOM` que vous avez écrite montre ce que React fait sous le capot lorsque vous définissez l’état. (Cependant, React évite également de toucher le DOM pour les propriétés qui n’ont p
```suggestion
La fonction `updateDOM` que vous avez écrite montre ce que React fait sous le capot lorsque vous définissez l’état. (Cependant, React évite également de redéfinir les aspects du DOM qui n’ont pas bougé depuis la dernière mise à jour.)
```

2023-04-28 22:59 UTC, tdd approved these changes

2023-04-28 23:00 UTC, merged