Translation of the "useId" page from API references
reactjs/fr.react.dev pull request #467
Opened 2023-05-05 16:35 UTC by MatteoGauthier

Salut 👋 ! Voici ma PR pour la traduction de la page `reference/react/useId` de la documentation

2023-05-12 14:30 UTC, tdd requested changes
Salut @MatteoGauthier !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Écoute au global c'est franchement pas mal ! 👏 

Un peu trop de "cela" au lieu de "ça", quelques tournures ampoulées en français par proximité trop forte avec la VO, une ou deux grosses fautes, mais ça reste bien cool !

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-05-12 14:30 UTC, tdd commented on src/content/reference/react/useId.md
> +Il est très difficile de garantir cela avec un compteur incrémentiel, car l'ordre dans lequel les composants du client sont hydratés peut ne pas correspondre à l'ordre dans lequel le code HTML du ser
```suggestion
Il est très difficile de garantir ça avec un compteur incrémental, car l'ordre dans lequel les composants côté client sont hydratés peut ne pas correspondre à l'ordre dans lequel le code HTML du serveur est émis. En appelant `useId`, vous vous assurez que l'hydratation fonctionnera et que la sortie correspondra entre le serveur et le client.
```

2023-05-12 14:30 UTC, tdd commented on src/content/reference/react/useId.md
> +  <head><title>Mon app</title></head>
```suggestion
  <head><title>Mon appli</title></head>
```

2023-05-15 07:12 UTC, MatteoGauthier commented on src/content/reference/react/useId.md
> +**Prenons un exemple pour mieux saisir l'utilité de cette méthode.**
👍

2023-05-17 08:59 UTC, tdd commented
@MatteoGauthier peux-tu trouver prochainement le temps de traiter ma revue stp ? 😉

2023-05-17 12:19 UTC, MatteoGauthier commented
Hello @tdd, désolé pour la latence 😅. J'ai accepté toutes tes propositions de changement.  Merci à toi pour tous tes conseils 🙏 (je crois que j'ai un problème avec les "cela")

2023-05-17 14:32 UTC, tdd approved these changes

2023-05-17 14:33 UTC, merged