[DRAFT]: doc(adding_interactivity): translate in french
reactjs/fr.react.dev pull request #468
Opened 2023-05-06 10:38 UTC by pfongkye

2023-05-13 12:38 UTC, tdd requested changes
Salut @pfongkye !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Et écoute, franchement c'est du super boulot.  Tu utilises "cela" au lieu de "ça" tout le temps, et parfois tes tournures sont un peu ampoulées car trop proches de la VO, mais y'a vraiment un super taf, en particulier sur les paragraphes longs.

Très beau boulot aussi sur les descriptifs d’œuvres d’art ; j'ai pas voulu vérifier si tu avais utilisé les trads Wikipedia 😉 

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +## Le rendu et la mise à jour {/*render-and-commit*/}
```suggestion
## Rendu et Commit {/*render-and-commit*/}
```

cf. remarque sidebar

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Imaginez que vos composants soient des cuisiniers dans un restaurant, assemblant des plats savoureux à partir d'ingrédients. Dans ce scénario, React est le serveur qui prend les commandes des clients
```suggestion
Imaginez que vos composants soient des cuisiniers dans un restaurant, assemblant des plats savoureux à partir d'ingrédients. Dans ce scénario, React est le serveur qui prend les commandes des clients et leur apporte leurs plats. Ce processus de demande et de service de l'UI comporte trois étapes :
```

On évite autant que possible les subordonnées ou groupes nominaux basés sur un infinitif, c'est ampoulé.

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +1. **Déclencher** un rendu (livrer la commande du client à la cuisine)
```suggestion
1. **Déclencher** un rendu (envoyer la commande du client à la cuisine)
```

"livrer" est trop connoté dans l'autre sens

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +3. **Mettre à jour** le DOM (placer la commande sur la table du client)
```suggestion
3. **Mettre à jour** le DOM (phase de Commit ;  revient à déposer la commande sur la table du client)
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +  <Illustration caption="Mettre à jour" alt="React livre Card à l'utilisateur à sa table." src="/images/docs/illustrations/i_render-and-commit3.png" />
```suggestion
  <Illustration caption="Mettre à jour (Commit)" alt="React dépose le Card sur la table de l’utilisateur." src="/images/docs/illustrations/i_render-and-commit3.png" />
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Lisez **[Le rendu et la mise à jour](/learn/render-and-commit)** pour apprendre sur le cycle de vie de la mise à jour d'une interface utilisateur.
```suggestion
Lisez **[Rendu et Commit](/learn/render-and-commit)** pour apprendre sur le cycle de vie d’une mise à jour de l’interface.
```

Léger glissement sémantique. Par ailleurs, on entrelace "UI" et "interface" selon l'humeur au lieu du loooong "interface utilisateur", qu'on a relié à l'abréviation en début de page.

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +## L'état comme une capture {/*state-as-a-snapshot*/}
```suggestion
## L'état comme un instantané {/*state-as-a-snapshot*/}
```

cf. remarque sidebar

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Contrairement aux variables JavaScript classiques, une variable d'état de React se comporte plus comme une capture à un instant T. Lui affecter une nouvelle valeur ne change pas la variable d'état qu
```suggestion
Contrairement aux variables JavaScript classiques, une variable d'état dans React se comporte davantage comme une photo instantanée. Lui affecter une nouvelle valeur ne change pas la variable d'état que vous avez déjà, mais déclenche plutôt un nouveau rendu. Ça peut surprendre au début !
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +console.log(count);  // Toujours 0!
```suggestion
console.log(count);  // Toujours 0 !
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +setCount(count + 1); // Déclenche un nouveau rendu avec la valeur 1
```suggestion
setCount(count + 1); // Entraînera un nouveau rendu avec la valeur 1
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Ce comportement vous aide à éviter des bugs subtils. Voici une petite application de chat. Essayez de deviner ce qui se passe si vous appuyez sur "Envoyer" d'abord, *puis* changez le destinataire en
```suggestion
Ce comportement vous aide à éviter des bugs subtils. Voici une petite appli de discussion. Essayez de deviner ce qui se passe si vous appuyez sur « Envoyer » d'abord, *et ensuite* changez le destinataire pour Bob. Quel nom apparaîtra dans le `alert` cinq secondes plus tard ?
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +        À:{' '}
```suggestion
        À :{' '}
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Lisez **[L'état comme une capture](/learn/state-as-a-snapshot)** pour comprendre pourquoi un état semble "fixe" et immuable à l'intérieur des gestionnaires d'événements.
```suggestion
Lisez **[L'état comme un instantané](/learn/state-as-a-snapshot)** pour comprendre pourquoi un état semble « fixe » et immuable à l’intérieur des gestionnaires d’événements.
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +[L'état comme une capture](/learn/state-as-a-snapshot) explique pourquoi cela se produit. Affecter une nouvelle valeur à un état déclenche un nouveau rendu, mais ne change pas sa valeur dans le code
```suggestion
[L'état comme un instantané](/learn/state-as-a-snapshot) en explique la raison. Affecter une nouvelle valeur à un état déclenchera un nouveau rendu, mais ne change pas sa valeur dans le code en cours d’exécution. Ainsi, `score` reste à `0` juste après avoir appelé `setScore(score + 1)`.
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Vous pouvez corriger cela en passant une *fonction de mise à jour* lorsque vous affectez une nouvelle valeur à l'état. Remarquez comment le remplacement de `setScore(score + 1)` par `setScore(s => s
```suggestion
Vous pouvez corriger ça en passant une *fonction de mise à jour* lorsque vous affectez une nouvelle valeur à l’état. Voyez comme le remplacement de `setScore(score + 1)` par `setScore(s => s + 1)` corrige le bouton "+3". Ça vous permet de cumuler plusieurs mises à jour d’un même état.
```

2023-05-13 12:38 UTC, tdd commented on src/sidebarLearn.json
> +          "title": "Mettre en file d'attente une série de mises à jour d'état",
```suggestion
          "title": "Cumuler les mises à jour d’un même état",
```

On parle ici de cumuler correctement des mises à jour d'une même varaible état (updater function plutôt que valeur). Cette formulation me semble un bon compromis entre concision et précision.

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +* [Comment mettre en file d'attente plusieurs mises à jour de l'état](/learn/queueing-a-series-of-state-updates)
```suggestion
* [Comment cumuler plusieurs mises à jour d’un même état](/learn/queueing-a-series-of-state-updates)
```

cf. remarque sidebar

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Lisez **[Mettre en file d'attente une série de mises à jour d'état](/learn/queueing-a-series-of-state-updates)** pour apprendre comment mettre en file d'attente une séquence de mises à jour d'état.
```suggestion
Lisez **[Cumuler les série de mises à jour d’un même état](/learn/queueing-a-series-of-state-updates)** pour apprendre comment cumuler plusieurs mises à jour d’une même variable d’état.
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Généralement, vous utiliserez la syntaxe de décomposition `...` pour copier les objets et les tableaux que vous souhaitez modifier. Par exemple, la mise à jour d'un objet imbriqué pourrait ressembler
```suggestion
Généralement, vous utiliserez la syntaxe de *spread* `...` pour copier les objets et les tableaux que vous souhaitez modifier. Par exemple, la mise à jour d'un objet imbriqué pourrait ressembler à ceci :
```

"décomposition" est sans doute mon seul vrai désaccord avec Julien "Sphinx", le principal traducteur FR du MDN 😉.  D'autant qu'il utilise ce terme pour le *spread* **et** pour la déstructuration.  Ce sont deux notions distinctes, et les termes "rest / spread" sont bien installés en usage francophone.

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Si la copie d'objets dans le code devient fastidieuse, vous pouvez utiliser une bibliothèque telle que [Immer](https://github.com/immerjs/use-immer) pour réduire le code répétitif :
```suggestion
Si la copie d'objets dans le code devient fastidieuse, vous pouvez utiliser une bibliothèque telle que [Immer](https://github.com/immerjs/use-immer) pour simplifier le code :
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Si la copie de tableaux dans le code devient fastidieuse, vous pouvez utiliser une bibliothèque telle que [Immer](https://github.com/immerjs/use-immer) pour réduire le code répétitif :
```suggestion
Si la copie de tableaux dans le code devient fastidieuse, vous pouvez utiliser une bibliothèque telle que [Immer](https://github.com/immerjs/use-immer) pour simplifier le code :
```

2023-05-13 12:38 UTC, tdd commented on src/content/learn/adding-interactivity.md
> +Allez sur [Répondre aux événements](/learn/responding-to-events) pour commencer à lire ce chapitre page par page !
```suggestion
Allez sur [Réagir aux événements](/learn/responding-to-events) pour commencer à lire ce chapitre page par page !
```

2023-05-15 07:08 UTC, pfongkye commented
Salut @tdd,
Merci beaucoup pour tes retours précieux. Je regarde ça dans la journée :+1:

2023-05-15 07:18 UTC, pfongkye commented on src/content/learn/adding-interactivity.md
> +  description: 'Bien que Colvin soit principalement connue pour ses thèmes abstraits qui font allusion à des symboles préhispaniques, cette sculpture gigantesque, un hommage à la neurochirurgie, est
Effectivement, j'ai recoupé avec Wikipedia VF quand c'était possible :sweat_smile:

2023-05-16 13:50 UTC, tdd approved these changes

2023-05-16 13:52 UTC, merged