doc(separating-events): french translation
reactjs/fr.react.dev pull request #471
Opened 2023-05-14 14:01 UTC by linsolas

Traduction de la page [Separating Events from Effects](https://react.dev/learn/separating-events-from-effects).

2023-05-21 15:34 UTC, linsolas commented
Hello @tdd,

J'ai refait une passe complète sur ma traduction à la suite de tes retours sur l'autre page.
Tu peux t'y atteler quand tu veux !

Merci.

2023-05-24 19:23 UTC, tdd requested changes
Salut @linsolas !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un gros coup de main.

Bon, je vais pas te mentir, c'était du taf. Ça sent la fatigue de ton côté, avec beaucoup de mot-à-mot dans les tournures de phrases, des incohérences de trad d'un bloc de code à l'autre (et par rapport aux pages établies qui ont le même code principal de *chat room*), etc.

Principaux points d'améliorations pour la suite :

1. Considère chaque phrase dans son intégralité au lieu de traduire au kilomètre. Parfois, une reformulation complète est pertinente, parfois juste un léger réordonnancement.
2. On italicise toujours *linter*
3. On dit "salon" ou "discussion" pour "chat", selon le contexte
4. Gaffe à reprendre les mêmes trads d'une page à l'autre pour les bouts de code utilisés partout (exemple de chat room notamment), par souci de cohérence.
5. Pas de rush, et pas de trad quand on est fatigué ! 😉 

Mais merci beaucoup, c'est quand même très cool ! 👍 

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-05-24 19:23 UTC, tdd commented on src/content/learn/separating-events-from-effects.md
> +  return <h1>Bienvenue sur le salon {roomId} !</h1>
```suggestion
  return <h1>Bienvenue dans le salon {roomId} !</h1>
```

2023-05-24 19:23 UTC, tdd commented on src/content/learn/separating-events-from-effects.md
> +    showNotification('Bienvenue au salon ' + connectedRoomId, theme);
```suggestion
    showNotification('Bienvenue dans le salon ' + connectedRoomId, theme);
```

Mais, tu vas nous faire combien de trads différentes ?!? 😂

2023-05-24 19:23 UTC, tdd commented on src/content/learn/separating-events-from-effects.md
> +Pour résoudre le défi supplémentaire, enregistrez l’ID du timer de notification and effacez-le dans la fonction de nettoyage de votre Effet :
```suggestion
Pour résoudre le défi supplémentaire, enregistrez l’ID du timer de notification et effacez-le dans la fonction de nettoyage de votre Effet :
```

2023-05-24 19:23 UTC, tdd commented on src/content/learn/separating-events-from-effects.md
> +        throw Error('Impossible d’ajouter le gestionnaire une seconde fois.');
```suggestion
        throw Error('Il n’est pas possible d’ajouter un gestionnaire deux fois.');
```

2023-05-24 19:23 UTC, tdd requested changes
Salut @linsolas !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un gros coup de main.

Bon, je vais pas te mentir, c'était du taf. Ça sent la fatigue de ton côté, avec beaucoup de mot-à-mot dans les tournures de phrases, des incohérences de trad d'un bloc de code à l'autre (et par rapport aux pages établies qui ont le même code principal de *chat room*), etc.

Principaux points d'améliorations pour la suite :

1. Considère chaque phrase dans son intégralité au lieu de traduire au kilomètre. Parfois, une reformulation complète est pertinente, parfois juste un léger réordonnancement.
2. On italicise toujours *linter*
3. On dit "salon" ou "discussion" pour "chat", selon le contexte
4. Gaffe à reprendre les mêmes trads d'une page à l'autre pour les bouts de code utilisés partout (exemple de chat room notamment), par souci de cohérence.
5. Pas de rush, et pas de trad quand on est fatigué ! 😉 

Mais merci beaucoup, c'est quand même très cool ! 👍 

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-05-28 08:51 UTC, linsolas commented
Hello @tdd 

Merci encore pour ta relecture attentive. C'est vrai que j'ai tendance à traduire phrase par phrase, il faut que je prenne l'habitude de relire ensuite l'ensemble du chapitre pour fluidifier le tout, sans avoir peur de trop m'éloigner du texte original.

J'attaque ma 3e page avec tout ça en tête 😉

2023-05-29 18:38 UTC, tdd approved these changes

2023-05-29 18:42 UTC, merged