Translation of the "Editor Config" page
reactjs/fr.react.dev pull request #475
Opened 2023-05-19 13:48 UTC by paulus85

PR pour la traduction de la page "Editor Config"

2023-05-19 13:51 UTC, paulus85 commented on src/content/learn/editor-setup.md
> +Certains éditeurs incluent ces fonctionnalités, mais d'autres pourraient demander d'installer des extensions. Vérifiez ce que propose votre éditeur préféré pour être sûr·e !
`Vérifiez ce que propose votre éditeur préféré pour être sûr·e !`

Pour l'inclusivité, est-ce que cette forme convient, ou il faut passer sur un mode "pour être sûrs" ?

2023-05-19 13:51 UTC, paulus85 commented on src/content/learn/editor-setup.md
> +* [Intégrer ESLint dans VSCode avec l'extension officielle](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
Plutôt infinitif ou impératif ici ?

2023-05-19 13:51 UTC, paulus85 commented on src/content/learn/editor-setup.md
> +> Si votre préréglage ESLint contient des règles de formatage, elles peuvent être en conflit avec Prettier. Nous recommandons de désactiver toutes les règles de formatage dans votre préréglage ESLint
J'ai préféré garder le terme "pull request" tel quel, n'hésitez pas à me dire s'il faut changer ou utiliser une autre typographie.

2023-05-23 06:50 UTC, tdd requested changes
Salut @paulus85 !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Écoute pour une première fois c'est pas mal du tout, quelques bonnes initiatives et de bons questionnements.  Le gros des ajustements proposés tient de la fluidification (parfois un peut trop de mot-à-mot), plus quelques nuances manquantes et un faux-ami.  Rien de méchant !

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +Un éditeur correctement configuré rend le code plus clair à lire et plus rapide à écrire. Il peut aussi vous aider à corriger les bugs dès que vous les écrivez ! Si c'est la première fois que vous co
```suggestion
Un éditeur correctement configuré peut faciliter la lecture du code et accélérer son écriture. Il peut même vous aider à corriger les bugs dès que vous les écrivez ! Si c'est la première fois que vous configurez un éditeur, ou si vous cherchez à améliorer votre éditeur actuel, nous avons quelques recommandations. 
```

Ton original est correct, mais il est parfois bon de reformuler pour plus de fluidité. Attention aux adverbes et auxiliaires cependant, dont les nuances sont parfois perdues dans ta version.

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +* Comment formatter votre code automatiquement
```suggestion
* Comment formater votre code automatiquement
```

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +[VS Code](https://code.visualstudio.com/) est l'un des éditeurs les plus populaires aujourd'hui. Il a un grand magasin d'extensions et s'intègre bien avec des services populaires comme GitHub. La plu
```suggestion
[VS Code](https://code.visualstudio.com/) est l'un des éditeurs les plus populaires aujourd'hui. Il propose un large choix d'extensions et s'intègre bien avec des services populaires tels que GitHub. La plupart des fonctionnalités listées ci-dessous peuvent être ajoutées à VS Code _via_ des extensions, ce qui le rend très configurable !
```

Petite reformulation, sinon c'est bien ! 👍

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +Voici d'autres éditeurs utilisés dans la communauté React :
```suggestion
Voici d'autres éditeurs utilisés par la communauté React :
```

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +* [WebStorm](https://www.jetbrains.com/webstorm/) est un environnement de développement intégré (_Integrated Development Environment ou IDE, NdT_) spécialement conçu pour JavaScript.
```suggestion
* [WebStorm](https://www.jetbrains.com/webstorm/) est un environnement de développement intégré (EDI) spécialement conçu pour JavaScript.
```

Formatage de NdT impeccable, mais pour le coup l'abréviation FR est solidement ancrée, donc pas besoin 😁

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +* [Sublime Text](https://www.sublimetext.com/) supporte JSX et TypeScript, [la coloration syntaxique](https://stackoverflow.com/a/70960574/458193) et inclut l'autocomplétion.
```suggestion
* [Sublime Text](https://www.sublimetext.com/) prend nativement en charge JSX et TypeScript, [la coloration syntaxique](https://stackoverflow.com/a/70960574/458193) et l'autocomplétion.
```

Le "built-in" s'applique aux trois lots de fonctionnalités. Attention au faux-ami hyper classique "to support" -> "supporter", qui est en fait "prendre en charge" (on "supporte" un truc pénible, on "prend en charge" une capacité)

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +* [Vim](https://www.vim.org/) est un éditeur de texte extrêmement configurable créé pour rendre très efficace la création et l'édition de tout type de texte. Il est inclus sous le nom de "vi" dans la
```suggestion
* [Vim](https://www.vim.org/) est un éditeur de texte extrêmement configurable créé pour optimiser la création et l'édition de tout type de texte. Il est inclus sous le nom de "vi" dans la plupart des systèmes UNIX et dans Apple OS X.
```

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +Certains éditeurs incluent ces fonctionnalités, mais d'autres pourraient demander d'installer des extensions. Vérifiez ce que propose votre éditeur préféré pour être sûr·e !
```suggestion
Certains éditeurs incluent ces fonctionnalités d'entrée de jeu, mais d'autres pourraient nécessiter l'installation d'extensions. Vérifiez ce que propose votre éditeur préféré pour être sûr·e !
```

- On essaie d'éviter les subordonnées infinitives, qui sont pataudes ("demander d'installer").
- Ta forme inclusive est la bonne 👍

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +Les linters de code trouvent les problèmes dans votre code au moment où vous l'écrivez, ce qui vous aide à les corriger au plus tôt. [ESLint](https://eslint.org/) est un outil de lint populaire et op
```suggestion
Les *linters* (analyseurs statiques) de code trouvent les problèmes dans votre code au moment où vous l'écrivez, ce qui vous aide à les corriger au plus tôt. [ESLint](https://eslint.org/) est un *linter* populaire en logiciel libre pour JavaScript.
```

*Linter* fait partie des mots qu'on utilise systématiquement en anglais et en italiques.

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +* [Installer ESLint avec la configuration recommandée pour React](https://www.npmjs.com/package/eslint-config-react-app) (soyez sûr·e que vous avez [installé Node !](https://nodejs.org/en/download/cu
```suggestion
* [Installez ESLint avec la configuration recommandée pour React](https://www.npmjs.com/package/eslint-config-react-app) (assurez-vous d'avoir [installé Node !](https://nodejs.org/fr/download/current/))
```

- Quand l'URL cible existe en FR, on la décline.
- Si on dispose d'une formulation fluide ne nécessitant pas de forme inclusive, on la prend (c'est plus léger à la lecture et un peu plus accessible en vocalisation).

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +* [Intégrer ESLint dans VSCode avec l'extension officielle](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
```suggestion
* [Intégrez ESLint dans VSCode avec l'extension officielle](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
```

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +* [Intégrer ESLint dans VSCode avec l'extension officielle](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
C'est pas *évident* dans la VO, mais vu la forme (liste, etc.) je penche pour des instructions, donc un impératif. C'est bien de t'être posé la question ! 👍

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +**Assurez-vous que vous avez activé toutes les règles [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks) pour votre projet.** Elles sont essentielles et permettent
```suggestion
**Assurez-vous d'avoir activé toutes les règles [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks) pour votre projet.** Elles sont essentielles et permettent de corriger tôt les bugs les plus graves . Le préréglage [`eslint-config-react-app`](https://www.npmjs.com/package/eslint-config-react-app) les inclut déjà.
```

"Assurez-vous de" ou "Vérifiez que" sont les formes fluides.

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +La dernière chose que vous voulez avoir à faire quand vous partagez votre code avec un autre contributeur est d'entrer dans une discussion sur [tabulations contre espaces](https://www.google.com/sear
```suggestion
La dernière chose que vous aimeriez faire lorsque vous partagez votre code avec d'autres contributeurs, ce serait d'entrer dans une discussion sur les [tabulations vs. espaces](https://www.google.com/search?q=tabs+vs+spaces) ! Heureusement, [Prettier](https://prettier.io/) va nettoyer votre code en le reformatant pour qu'il soit conforme à des règles configurables prédéfinies. Exécutez Prettier, et toutes vos tabulations seront remplacées par des espaces--et vos indentations, guillemets, etc. seront aussi modifiés pour devenir conformes à la configuration. Dans l'idéal, Prettier s'exécute quand vous enregistrez votre fichier, et fait ces ajustements pour vous en un clin d'œil.
```

Franchement pas mal, même si ça appelait quelques lissages.

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +2. Utilisez Quick Open (appuyez sur Ctrl/Cmd+P)
```suggestion
2. Utilisez Quick Open (pressez Ctrl/Cmd+P)
```

On utilise sans problème "presser" pour des manips clavier.

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +2. Entrez "settings"
```suggestion
2. Tapez "settings"
```

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +> Si votre préréglage ESLint contient des règles de formatage, elles peuvent être en conflit avec Prettier. Nous recommandons de désactiver toutes les règles de formatage dans votre préréglage ESLint
```suggestion
> Si votre préréglage ESLint contient des règles de formatage, elles peuvent être en conflit avec Prettier. Nous recommandons de désactiver toutes les règles de formatage dans votre préréglage ESLint en utilisant [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) ; ainsi ESLint est utilisé *seulement* pour corriger les erreurs de logique. Si vous voulez que les fichiers soient formatés avant de fusionner une _pull request_, utilisez [`prettier --check`](https://prettier.io/docs/en/cli.html#--check) dans votre intégration continue.
```

2023-05-23 06:50 UTC, tdd commented on src/content/learn/editor-setup.md
> +> Si votre préréglage ESLint contient des règles de formatage, elles peuvent être en conflit avec Prettier. Nous recommandons de désactiver toutes les règles de formatage dans votre préréglage ESLint
Oui, clairement personne n'aime le "demandes de tirage" de certaines trads.  Pull request (ou Merge request pour GitLab, un terme d'ailleurs plus juste la plupart du temps) est très, très ancré dans le vocabulaire FR, donc on garde. Pas besoin des quotes, mais italiques.

2023-05-26 17:12 UTC, tdd commented
@paulus85 coucou ! Si tu peux consulter ma review et la traiter comme indiqué dans le message général, ce serait top pour qu'on puisse finaliser ta contrib' rapidement 😉

2023-05-26 21:25 UTC, paulus85 commented
Salut @tdd ! J'ai intégré tes retours, n'hésite pas à me dire s'il manque des choses !

2023-05-29 18:44 UTC, tdd approved these changes

2023-05-29 18:46 UTC, merged