Translation of the “React Developer Tools” page
reactjs/fr.react.dev pull request #479
Opened 2023-05-26 14:33 UTC by Ameliegre

Voici ma PR pour la page React Developer Tools 😀

2023-05-26 18:10 UTC, tdd requested changes
Salut @Ameliegre !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Bon, on a les petites bévues usuelles des primo-traducteurs. L'essentiel de mes suggestions va dans les catégories suivantes :

- Aspects typographiques
- Arbitrage incorrect français / anglais

Rien de bien méchant ! 😉 

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
> +* [Installation pour **Edge**](https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil)
```suggestion
* [Installer dans **Firefox**](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/)
* [Installer dans **Edge**](https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil)
```

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
> +Maintenant, si vous visitez un site Web **construit avec React,** vous pouvez apercevoir les onglets _Components_ et _Profiler_.
```suggestion
Désormais, si vous visitez un site web **construit avec React**, vous pouvez apercevoir les onglets _Components_ et _Profiler_.
```

- "Now," en début de phrase est rarement traduit par "Maintenant," plutôt par "Désormais," ou "À présent," suivant le contexte.
- "web" pour un adjectif, "Web" pour "le Web".
- La ponctuation finale ne reste pas dans le formatage (graisse ou italique), sauf si celui-ci comprend la phrase entière.

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
> +Puis, ouvrez les outils de développement depuis le terminal:
```suggestion
Ouvrez alors les outils de développement depuis le terminal :
```

"Puis," est inexistant en français.

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
> +Ensuite, connectez votre site en ajoutant la balise `<script>` suivante au debut de la balise `<head>` de votre site :
```suggestion
Ensuite, connectez votre site en ajoutant la balise `<script>` suivante au début de la balise `<head>` de votre site :
```

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
> +Maintenant, actualisez votre site dans le navigateur pour l'afficher dans les outils de développement.
```suggestion
Pour finir, rafraîchissez votre page dans le navigateur pour l'afficher dans les outils de développement. 
```

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
>  ## Mobile (React Native) {/*mobile-react-native*/}
La VO ne clarifie pas le distingo avec le web mobile, mais c'est pertinent.

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
> +La meilleure façon d'utiliser React Developer Tools est de l'installer au global:
```suggestion
La façon la plus simple d'utiliser les outils de développement React consiste à les installer au global :
```

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
> +Puis, ouvrez les outils de développement depuis le terminal:
```suggestion
Ouvrez alors les outils de développement depuis le terminal :
```

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
> +Cela devrait se connecter à toute Appli React Native locale en cours d'exécution.
```suggestion
Ça devrait se connecter à toute appli React Native locale en cours d'exécution.
```

2023-05-26 18:10 UTC, tdd commented on src/content/learn/react-developer-tools.md
> +> Essayez de relancer l'Appli si les outils de développement ne se connectent pas après quelques secondes.
```suggestion
> Essayez de relancer l'appli si les outils de développement ne se connectent pas au bout de quelques secondes. 
```

2023-05-28 19:32 UTC, Ameliegre commented
Je viens de commit les modifs, merci pour cette review!
Et oui en relisant la correction, c'est vrai qu'il y des choses qui paraissent logique ! On en apprends tous les jours 😊

2023-05-29 18:52 UTC, tdd approved these changes

2023-05-29 18:55 UTC, merged