Translation of the 'Add React to an Existing Project' page
reactjs/fr.react.dev pull request #483
Opened 2023-05-30 13:11 UTC by hakimLyon

🎉 Salut @tdd ! 
Je voulais vous informer que j'ai terminé la trad de la page 'Add React to an Existing Project'. 
Prêt pour votre revue.

2023-06-01 14:58 UTC, tdd commented
Coucou @hakimLyon ! OK, j'en prends note. J'aurai sans doute pas le temps aujourd'hui, mais probablement demain.

2023-06-01 20:24 UTC, tdd requested changes
Salut @hakimLyon !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Au global c'est très prometteur, bravo ! Y'a des petits couacs typographiques, des incohérences mineures dans tes choix syntaxiques, mais c'est vraiment pas mal du tout !

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +1. **Construisez la partie React de votre application** en utilisant l'un des [Frameworks basés sur React](/learn/start-a-new-react-project).
```suggestion
1. **Construisez la partie React de votre appli** en utilisant l'un des [frameworks basés sur React](/learn/start-a-new-react-project).
```

app -> appli, application -> application

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +2. **Spécifiez `/some-app` comme le *chemin de base*** dans la configuration de votre framework (voici comment le faire avec: [Next.js](https://nextjs.org/docs/api-reference/next.config.js/basepath),
```suggestion
2. **Indiquez`/some-app` comme *chemin de base*** dans la configuration de votre framework (voici comment faire avec [Next.js](https://nextjs.org/docs/api-reference/next.config.js/basepath) ou [Gatsby](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/)).
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +Cela garantit que la partie React de votre application peut [bénéficier des bonnes pratiques](/learn/start-a-new-react-project#can-i-use-react-without-a-framework) intégrées à ces frameworks.
```suggestion
Ça garantit que la partie React de votre application peut [bénéficier des bonnes pratiques](/learn/start-a-new-react-project#can-i-use-react-without-a-framework) intégrées à ces frameworks.
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +De nombreux frameworks basés sur React sont des frameworks full-stack qui permettent à votre application React de tirer parti du serveur. Cependant, vous pouvez utiliser la même approche même si vous
```suggestion
De nombreux frameworks basés sur React sont des frameworks full-stack qui permettent à votre application React de tirer parti du serveur. Cependant, vous pouvez utiliser la même approche même si vous ne pouvez pas ou ne souhaitez pas exécuter JavaScript côté serveur. Dans ce cas, servez plutôt l'export HTML/CSS/JS ([`next export`](https://nextjs.org/docs/advanced-features/static-html-export) pour Next.js, résultat par défaut pour Gatsby) à l'emplacement `/some-app/`.
```

"Exportation" désigne un traitement, "Export" un livrable dans un contexte tech. À part ça, vraiment bien ! 👍

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +Supposons que vous avez une page existante construite avec une autre technologie (soit une technologie côté serveur comme Rails, soit une technologie côté client comme Backbone), et que vous souhaiti
```suggestion
Supposons que vous ayez une page existante construite avec une autre technologie (soit côté serveur, comme Rails ; soit côté client, comme Backbone), et que vous souhaitiez afficher des composants React interactifs à un endroit spécifique de cette page. C'est une façon courante d'intégrer React--en fait, c'est ainsi que la plupart des utilisations de React étaient mises en place chez Meta pendant de nombreuses années !
```

- Derrière "imaginer" ou "supposer", on utilisera le subjonctif. Derrière "disons", plutôt l'indicatif. Tu as d'ailleurs utilisé le subjonctif plus haut… et dans la subordonnée.

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +1. **Mettre en place un environnement JavaScript** qui vous permet d'utiliser la [syntaxe JSX](/learn/writing-markup-with-jsx), de diviser votre code en modules avec la syntaxe [`import`](https://dev
```suggestion
1. **Mettez en place un environnement JavaScript** qui vous permette d'utiliser la [syntaxe JSX](/learn/writing-markup-with-jsx), de diviser votre code en modules avec la syntaxe [`import`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/import) / [`export`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/export), et d'utiliser des packages (par exemple, React) provenant du référentiel de modules [npm](https://www.npmjs.com/).
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +2. **Afficher vos composants React** là où vous souhaitez les voir sur la page.
```suggestion
2. **Affichez vos composants React** là où vous souhaitez les voir sur la page.
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +### Étape 1 : Mettre en place un environnement JavaScript modulaire {/*step-1-set-up-a-modular-javascript-environment*/}
```suggestion
### Étape 1 : mettez en place un environnement JavaScript modulaire {/*step-1-set-up-a-modular-javascript-environment*/}
```

Pas de majuscule après les deux-points en FR.

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +* **Si votre application est déjà divisée en fichiers qui utilisent des déclarations `import`,** essayez d'utiliser la configuration que vous avez déjà. Vérifiez si l'écriture de `<div />` dans votre
```suggestion
* **Si votre application est déjà divisée en fichiers qui utilisent des déclarations `import`**, essayez d'utiliser la configuration que vous avez déjà. Vérifiez si l'écriture de `<div />` dans votre code JS provoque une erreur de syntaxe.  Si tel est le cas, vous devrez peut-être [transformer votre code JavaScript avec Babel](https://babeljs.io/setup), et activer le [préréglage Babel React](https://babeljs.io/docs/babel-preset-react) pour utiliser JSX.
```

Pas de ponctuation finale dans les graisses et italiques (on la sort), sauf si toute la phrase est enveloppée. (Dans le même esprit, jamais de ponctuation en fin de lien, on la sort toujours.)

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +* **Si votre application n'a pas de configuration existante pour la compilation des modules JavaScript,** mettez-la en place avec [Vite](https://vitejs.dev/). La communauté Vite propose de [nombreuse
```suggestion
* **Si votre application n'a pas de configuration existante pour la compilation des modules JavaScript**, mettez-en une en place avec [Vite](https://vitejs.dev/). La communauté Vite propose de [nombreuses intégrations avec des frameworks backend](https://github.com/vitejs/awesome-vite#integrations-with-backends), notamment Rails, Django et Laravel. Si votre framework backend ne figure pas dans leur liste, [suivez ce guide](https://vitejs.dev/guide/backend-integration.html) pour intégrer manuellement les builds Vite à votre backend.
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +Ensuite, ajoutez ces lignes de code en haut de votre fichier JavaScript principal (il pourrait s'appeler `index.js` ou `main.js`):
```suggestion
Ensuite, ajoutez ces lignes de code en haut de votre fichier JavaScript principal (il pourrait s'appeler `index.js` ou `main.js`) :
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +Cela vous permet de trouver cet élément HTML avec [`document.getElementById`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById) et de le transmettre à [`createRoot`](/referenc
```suggestion
Ça vous permettra de trouver cet élément HTML avec [`document.getElementById`](https://developer.mozilla.org/fr/docs/Web/API/Document/getElementById) et de le transmettre à [`createRoot`](/reference/react-dom/client/createRoot) afin de pouvoir afficher votre propre composant React à l'intérieur :
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
>    return <h1>Hello from React!</h1>;
```suggestion
  return <h1>React vous dit bonjour !</h1>;
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +Remarquez comment le contenu HTML d'origine de `index.html` est préservé, mais votre propre composant React `NavigationBar` apparaît maintenant à l'intérieur de la balise `<nav id="navigation">` de v
```suggestion
Voyez comme le contenu HTML d'origine de `index.html` est préservé, alors que votre propre composant React `NavigationBar` apparaît désormais à l'intérieur de la balise `<nav id="navigation">` de votre HTML. Allez voir [la documentation sur l'utilisation de `createRoot`](/reference/react-dom/client/createRoot#rendering-a-page-partially-built-with-react) pour en savoir plus sur l'affichage des composants React à l'intérieur d'une page HTML existante.
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +Lorsque vous adoptez React dans un projet existant, il est courant de commencer par de petits composants interactifs (comme des boutons), puis de progressivement "monter en gamme" jusqu'à ce que fina
```suggestion
Lorsque vous adoptez React dans un projet existant, il est courant de commencer par de petits composants interactifs (comme des boutons), puis de progressivement « monter en gamme » jusqu'à ce que finalement l'ensemble de votre page soit construit avec React. Si vous en arrivez là, nous vous recommandons de migrer vers [un framework React](/learn/start-a-new-react-project) pour tirer le meilleur parti de React.
```

2023-06-01 20:24 UTC, tdd commented on src/content/learn/add-react-to-an-existing-project.md
> +[React Native](https://reactnative.dev/) peut également être intégré progressivement dans des applications natives existantes. Si vous avez une application native existante pour Android (Java ou Kotl
```suggestion
[React Native](https://reactnative.dev/) peut également être intégré progressivement dans des applis natives existantes. Si vous avez une appli native existante pour Android (Java ou Kotlin) ou iOS (Objective-C ou Swift), [suivez ce guide](https://reactnative.dev/docs/integration-with-existing-apps) pour ajouter un écran React Native à celle-ci.
```

2023-06-02 01:34 UTC, hakimLyon commented on src/content/learn/add-react-to-an-existing-project.md
> +Si vous souhaitez apporter de l'interactivité à votre projet existant, vous n'avez pas besoin de le réécrire entièrement en React. Ajoutez simplement React à votre pile technologique existante et aff
Compris, nous garderons l'expression "pile technologique" 😊.

2023-06-02 21:01 UTC, tdd commented
@hakimLyon si tu peux prendre le temps de traiter les retours comme indiqué dans mon commentaire de revue, ça me permettra de faire la revue visuelle finale et de *merger* dans `main`.

2023-06-03 00:28 UTC, hakimLyon commented
Salut @tdd d'accord tout de suite. 
Désolé pour le retard.

2023-06-04 09:04 UTC, tdd approved these changes

2023-06-04 17:17 UTC, merged