Translation of the 'useDeferredValue' page
reactjs/fr.react.dev pull request #484
Opened 2023-05-30 22:48 UTC by nina-alin

Traduction de la page "useDeferredValue". Étant donné qu'il s'agit de ma première traduction, je vous laisse me donner tous vos meilleurs conseils !

2023-05-31 09:58 UTC, tdd requested changes
Salut @nina-alin !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Bon, tu as choisi pour ta première trad de t'attaquer à un gros morceau (en volume), avec en plus des nuances techniques assez fines.  Gros challenge ! C'est pourquoi y'a pas mal de retours.

Je n'ai pas reporté jusqu'au bout des correctifs au sein des exemples de code (car c'est souvent le même code pour les exemples), mais je te l'ai signalé, et donc il te faudra, après gestion dans GitHub, *puller* localement et finaliser les reports appropriés (au pire, je m'en chargerai en passe de revue locale finale).

Écoute c'est pas mal du tout pour une première. Lis attentivement les retours, mais en gros, les principaux points à améliorer sont les suivants :

- On ne dira jamais "re-render" (encore moins comme un verbe) en FR. On dira suivant le cas "rendu", "nouveau rendu", "refaire un/son rendu", etc.
- Oublie les futurs proches ("il va faire") au profit des futurs simples ("il fera").
- Typographie (moins grave car je repasse toujours dessus, mais bon) : espaces insécables devant les signes de ponctuation doubles, pas de majuscules derrière les deux-points, guillemets français, etc.
- Pas de ponctuation en fin de texte de lien (après, plutôt), ni en fin de graisses / italiques sauf si celles-ci enrobent la phrase entière.
- "Délayer", c'était raté. Pas de bol, c'est là 1000 fois 😨. J'ai systématiquement ajusté, y compris quand tu disais soudainement "reporter".
- D'une façon générale, y'a quelques glissements sémantiques. Si tu as un doute sur le sens de certaines phrases, n'hésite pas à ouvrir ta PR en *draft* pour solliciter des retours via des commentaires GitHub localisé où tu me @-quotes pour que je soie notifié.
T'inquiète, ça reste très bien, et on est tou·te·s passé·e·s par là ! 😁 

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +// qui n'est pas encore disponible dans les versions stables de React.
```suggestion
// Remarque : ce composant est écrit en utilisant une API expérimentale
// qui n'est pas encore disponible dans les versions stables de React.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +    return <p>Pas de résultats pour <i>"{query}"</i></p>;
```suggestion
    return <p>Pas de résultat pour <i>« {query} »</i></p>;
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +// TODO: remplacer avec la vraie implémentation quand le bug sera fixé.
```suggestion
// Astuce de contournement d'un bug afin d'exécuter la démo. 
// TODO: remplacer avec la véritable implémentation quand le bug sera corrigé.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +#### Comment délayer une valeur fonctionne-t-il en sous-jacent ? {/*how-does-deferring-a-value-work-under-the-hood*/}
```suggestion
#### Comment une valeur différée fonctionne-t-elle sous le capot ? {/*how-does-deferring-a-value-work-under-the-hood*/}
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Vous pouvez imaginer le déroulement en deux étapes :
```suggestion
Imaginez un déroulement en deux étapes :
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +1. **Premièrement, React re-renders avec la nouvelle `query` (`"ab"`) mais avec l'ancienne `deferredQuery` (toujours `"a")`.** La valeur `deferredQuery`, à laquelle vous passez la liste de résultats,
```suggestion
1. **Pour commencer, React refait un rendu avec la nouvelle `query` (`"ab"`) mais avec l'ancienne `deferredQuery` (toujours `"a")`.** La valeur `deferredQuery`, que vous passez à la liste de résultats, est *différée* : elle est « en retard » par rapport à la valeur `query`.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +2. **En arrière-plan, React essaye de re-render avec `query` et `deferredQuery` mis à jour *ensemble* avec `"ab"`.** Si ce re-render réussi, React vous le montre sur l'écran. Cependant, s'il se suspe
```suggestion
2. **En arrière-plan, React tente alors un autre rendu avec `query` et `deferredQuery` valant *toutes les deux* `"ab"`.** Si ce rendu aboutit, React l'affichera à l'écran. Cependant, s'il suspend (les résultats pour `"ab"` ne sont pas encore chargés), React abandonnera cet essai de rendu, et essaiera à nouveau une fois les données chargées. L'utilisateur continuera à voir l'ancienne valeur différée jusqu'à ce que les données soient prêtes. 
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Le rendu de "l'arrière-plan" délayé est susceptible d'être interrompu. Par exemple, si vous tapez dans la zone de saisie à nouveau, React va l'abandonner et recommencer avec la nouvelle valeur. React
```suggestion
Le rendu différé « d'arrière-plan » est susceptible d'être interrompu. Par exemple, si vous tapez à nouveau dans le champ de saisie, React l'abandonnera et recommencera avec la nouvelle valeur. React utilisera toujours la dernière valeur fournie.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Notez qu'il y a toujours une requête réseau par frappe au clavier. Ce qui est reporté ici est l'affichage des résultats (jusqu'à ce qu'ils soient prêts), et non pas les requêtes réseaux en elle-mêmes
```suggestion
Remarquez qu'il y a quand même une requête réseau par frappe clavier. Ce qui est différé ici, c'est l'affichage des résultats (jusqu'à ce qu'ils soient prêts), et non pas les requêtes réseau elles-mêmes. Même si l'utilisateur continue à saisir, les réponses pour chaque frappe clavier sont mises en cache, donc les données ne sont pas chargées à nouveau lorsqu'on appuie sur Backspace : la mise à jour est alors instantanée.
```

Quelques glissements sémantiques (j'ai beaucoup aimé Backspace -> Espace 😉)

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Dans l'exemple ci-dessous, il n'y aucune indication montrant que la liste des résultats est toujours en train de charger, et qu'elle prend en compte la dernière recherche. Cela peut être dérangeant p
```suggestion
Dans l'exemple ci-avant, il n'y aucune indication que la liste des résultats pour la dernière requête est toujours en train de charger. Cela peut être déroutant pour l'utilisateur si les nouveaux résultats prennent du temps à charger. Afin de bien signifier que la liste de résultats ne reflète pas encore la dernière recherche, vous pouvez ajouter une indication visuelle lorsque l'ancienne liste de résultats est affichée :
```

- "Above" ≠ "Below"
- Confusion sémantique
- C'est quoi ces espaces en fin de ligne à chaque fois ?

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Avec ce changement, dès que vous commencerez à taper, l'ancienne liste de résultats sera légèrement transparente, jusqu'à ce que la nouvelle liste de résultats soit chargée. Vous pouvez également ajo
```suggestion
Avec ce changement, dès que vous commencerez à taper, l'ancienne liste de résultats sera légèrement assombrie, jusqu'à ce que la nouvelle liste de résultats soit chargée. Vous pouvez également ajouter une transition CSS pour un résultat plus graduel, comme dans l'exemple ci-dessous :
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +### Délayer le rendu d'une partie de l'UI {/*deferring-re-rendering-for-a-part-of-the-ui*/}
```suggestion
### Différer le rendu d'une partie de l'UI {/*deferring-re-rendering-for-a-part-of-the-ui*/}
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Vous pouvez également utiliser `useDeferredValue` pour optimiser les performances. Cette manière de faire est utile lorsqu'une partie de votre UI est lente à re-render, qu'il n'y a pas de manière fac
```suggestion
Vous pouvez également utiliser `useDeferredValue` pour optimiser les performances. C'est pratique lorsqu'une partie de votre UI a un rendu lent, qu'il n'y a pas de manière simple de l'optimiser, et que vous voulez éviter qu'elle bloque le reste de l'UI.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Imaginez que vous avez une zone de saisie de texte et un composant (comme un graphique ou une longue liste) qui re-renders à chaque frappe sur le clavier :
```suggestion
Imaginez que vous avez un champ textuel et un composant (comme un graphique ou une longue liste) qui refait son rendu à chaque frappe clavier :
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +D'abord, optimisez `SlowList` pour éviter le re-render lorsque ses propriétés sont les mêmes. Pour se faire, [enveloppez-le dans `memo`:](/reference/react/memo#skipping-re-rendering-when-props-are-un
```suggestion
Pour commencer, optimisez `SlowList` pour éviter un nouveau rendu quand ses propriétés n'ont pas changé. Pour ce faire, [enrobez-le avec `memo`](/reference/react/memo#skipping-re-rendering-when-props-are-unchanged) :
```

Trad établie pour "wrap" (on préfère "enrober" à "envelopper", tout aussi valable mais plus long, d'autant qu'on dit couramment "enrobage" aussi dans la tech).

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Cependant, cette manière de faire n'est utile que si les propriétés de `SlowList` sont *les mêmes* que pendant le rendu précédent. Ce composant peut toujours être lent lorsque les propriétés sont *di
```suggestion
Cependant, ça ne vous aide que si les propriétés de `SlowList` sont *les mêmes* que lors du rendu précédent. Ce composant peut toujours être lent lorsque les propriétés sont *différentes*, et que vous avez effectivement besoin de produire un rendu visuel distinct.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Concrètement, le problème de performances est causé lorsque vous tapez dans le champ de saisie. La `SlowList` reçoit des nouvelles propriétés à chaque frappe, et l'écriture est saccadée. Son arbre en
```suggestion
Concrètement, le souci de performances principal vient de ce que lorsque vous tapez dans le champ de saisie, la `SlowList` reçoit des nouvelles propriétés, et la lenteur de sa mise à jour rend la saisie saccadée. Dans un tel cas, `useDeferredValue` vous permet de prioriser la mise à jour du champ de saisie (qui doit être rapide) par rapport à celle de la liste de résultats (qui peut être plus lente) :
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Cela ne rend pas le nouveau rendu de `SlowList` plus rapide. Cependant, cela dit à React que rendre la liste peut être dépriorisé afin de ne pas bloquer les frappes au clavier. La liste va "être en r
```suggestion
Ça n'accélère pas le rendu de `SlowList`. Néanmoins, ça indique à React de déprioriser le rendu de la liste afin de ne pas bloquer les frappes clavier. La liste sera « en retard » par rapport au champ de saisie, pour finalement le « rattraper ». Comme auparavant, React essaiera de mettre à jour la liste le plus vite possible, mais sans empêcher l'utilisateur de taper.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +<Recipes titleText="La différence entre useDeferredValue et le rendu non optimisé" titleId="examples">
```suggestion
<Recipes titleText="Différence entre useDeferredValue et un rendu non optimisé" titleId="examples">
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +#### Reporter le rendu d'une liste {/*deferred-re-rendering-of-the-list*/}
```suggestion
#### Différer le rendu de la liste {/*deferred-re-rendering-of-the-list*/}
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Dans cet exemple, chaque élément du composant `SlowList` est **artificiellement ralenti** afin que vous puissiez observer comment `useDeferredValue` permet de garder ce champ de saisie réactif. Écriv
```suggestion
Dans cet exemple, chaque élément du composant `SlowList` est **artificiellement ralenti** afin que vous puissiez constater que `useDeferredValue` permet de garder le champ de saisie réactif. Écrivez dans le champ de saisie et voyez comme la saisie reste réactive, alors que la liste « est en retard ».
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +      Texte: {text}
```suggestion
      Texte : {text}
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Vous pouvez remarquer que la frappe dans le champ de saisie est très saccadée. Sans `useDeferredValue`, chaque frappe au clavier force la liste entière à re-render immédiatement et de manière inarrêt
```suggestion
Vous pouvez remarquer que la frappe dans le champ de saisie est très saccadée. Sans `useDeferredValue`, chaque frappe clavier force la liste entière à refaire un rendu immédiatement, sans possibilité d'interruption.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +L'optimisation nécessite que `SlowList` soit accompagnée d'un [`memo`.](/reference/react/memo) À chaque fois que `text` change, React a besoin d'être capable de re-render le composant parent rapideme
```suggestion
Cette optimisation nécessite que `SlowList` soit enrobée par un [`memo`](/reference/react/memo). En effet, à chaque fois que `text` change, React doit pouvoir refaire le rendu du composant parent rapidement. Durant ce rendu, `deferredText` a toujours sa valeur précédente, donc `SlowList` peut s'épargner un nouveau rendu (ses propriétés n'ont pas changé). Sans [`memo`](/reference/react/memo), il y aurait un nouveau rendu dans tous les cas, ce qui tue tout l'intérêt de l'optimisation.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +#### Quelle est la différence entre reporter une valeur et le debouncing et le throttling ? {/*how-is-deferring-a-value-different-from-debouncing-and-throttling*/}
```suggestion
#### Valeur différée, *debouncing* et *throttling* : quelles différences ? {/*how-is-deferring-a-value-different-from-debouncing-and-throttling*/}
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Il existe deux technique d'optimisation communes que vous avez pu peut-être utiliser auparavant dans ce genre de scénarios :
```suggestion
Il existe deux technique d'optimisation courantes que vous avez peut-être utilisées auparavant dans ce genre de scénarios :
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +- *Debouncing* signifie que vous attendez qu'un utilisateur arrête de taper (par exemple pendant une seconde) avant de mettre à jour la liste.
```suggestion
- Le *debouncing* signifie que vous attendriez que l'utilisateur cesse de taper (par exemple pendant une seconde) avant de mettre à jour la liste.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +- *Throttling* signifie que vous mettez à jour la liste à un temps donné (par exemple toutes les secondes).
```suggestion
- Le *throttling* signifie que vous ne mettriez à jour la liste qu'à une fréquence limitée (par exemple au maximum une fois par seconde).
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Mêmes si ces techniques sont utiles dans certains cas, `useDeferredValue` est plus adapté pour optimiser le rendu, car il est totalement intégré avec React et il s'adapte au support de l'utilisateur.
```suggestion
Mêmes si ces techniques sont utiles dans certains cas, `useDeferredValue` est plus adapté pour optimiser le rendu, car il est totalement intégré avec React et il s'adapte à l'appareil de l'utilisateur.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +De plus, les rendu reportés réalisés par `useDeferredValue` sont susceptibles d'être interrompus par défaut, ce qui n'est pas le cas du debouncing ou du throttling. Cela signifie que si React est au
```suggestion
De plus, les rendus différés planifiés par `useDeferredValue` sont par défaut susceptibles d'être interrompus, ce qui n'est pas le cas du *debouncing* ou du *throttling*. Ça signifie que si React est en plein milieu du rendu d'une vaste liste, et que l'utilisateur ajuste sa saisie, React abandonnera ce rendu, traitera la frappe, et recommencera le rendu en arrière-plan. Par opposition, le *debouncing* et le *throttling* donneraient ici toujours une expérience saccadée car ils sont *bloquants* : ils diffèrent simplement le moment auquel le rendu bloque la frappe.
```

2023-05-31 09:58 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +Si vous souhaitez optimiser des éléments qui n'arrivent pas pendant le rendu, le debouncing et le throttling sont toujours utiles. Par exemple, ils peuvent vous laisser entamer moins de requêtes rése
```suggestion
Si vous souhaitez optimiser des traitements hors du rendu, le *debouncing* et le *throttling* restent utiles. Par exemple, ils peuvent vous permettre de lancer moins de de requêtes réseau. Vous pouvez parfaitement combiner ces techniques. 
```

2023-05-31 09:58 UTC, tdd requested changes
Salut @nina-alin !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Bon, tu as choisi pour ta première trad de t'attaquer à un gros morceau (en volume), avec en plus des nuances techniques assez fines.  Gros challenge ! C'est pourquoi y'a pas mal de retours.

Je n'ai pas reporté jusqu'au bout des correctifs au sein des exemples de code (car c'est souvent le même code pour les exemples), mais je te l'ai signalé, et donc il te faudra, après gestion dans GitHub, *puller* localement et finaliser les reports appropriés (au pire, je m'en chargerai en passe de revue locale finale).

Écoute c'est pas mal du tout pour une première. Lis attentivement les retours, mais en gros, les principaux points à améliorer sont les suivants :

- On ne dira jamais "re-render" (encore moins comme un verbe) en FR. On dira suivant le cas "rendu", "nouveau rendu", "refaire un/son rendu", etc.
- Oublie les futurs proches ("il va faire") au profit des futurs simples ("il fera").
- Typographie (moins grave car je repasse toujours dessus, mais bon) : espaces insécables devant les signes de ponctuation doubles, pas de majuscules derrière les deux-points, guillemets français, etc.
- Pas de ponctuation en fin de texte de lien (après, plutôt), ni en fin de graisses / italiques sauf si celles-ci enrobent la phrase entière.
- "Délayer", c'était raté. Pas de bol, c'est là 1000 fois 😨. J'ai systématiquement ajusté, y compris quand tu disais soudainement "reporter".
- D'une façon générale, y'a quelques glissements sémantiques. Si tu as un doute sur le sens de certaines phrases, n'hésite pas à ouvrir ta PR en *draft* pour solliciter des retours via des commentaires GitHub localisé où tu me @-quotes pour que je soie notifié.
T'inquiète, ça reste très bien, et on est tou·te·s passé·e·s par là ! 😁 

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-05-31 21:40 UTC, nina-alin commented
Salut @tdd ! 

J'ai bien pris en compte toute tes remarques. Je t'en remercie grandement ! Elles sont toutes constructives et intéressantes. J'en prends bien note, en particulier pour les nombreux changements récurrents que tu as pu faire  (les espaces inutiles, les "Remarque" au lieu de "Note", la formulation de certaines phrases, le _re-render_, etc). Pour la partie purement syntaxique, concernant la tournure des phrases, j'ai l'impression que ça s'apprend en faisant. Je vois pas mal de phrases qui me semblaient bien à l'écriture et aux relectures, et tes commentaires me font prendre conscience que j'étais parfois un peu à côté de la plaque :sweat_smile:  

Je t'ai laissé deux issues non _resolved_ avec deux points qui m'ont posé question. J'ai tout de même _commit_ les changements concernés, car je n'étais pas fondamentalement en désaccord avec toi sur ces points :wink: 

J'ai conscience d'avoir pris un morceau assez compliqué dès le début. En général, dans des domaines que je ne connais pas, je met toujours la barre assez haute, d'où le choix de `useDeferredValue` :wink: . C'est ce qui me permet réellement d'apprendre. Mais du coup, tu as du prendre pas mal de temps à tout corriger. Si pour la prochaine traduction, tu préfères que je prenne un fichier moins complexe à traduire, fais-le moi savoir. 

Egalement, j'avais une question concernant l'historique des commits : est-ce que tu veux que j'_amend_ mes commits afin d'avoir un historique un maximum clair, ou vous ne prêtez pas spécialement attention à ce point ? Comme tu peux voir, je n'ai pas poussé ma traduction en un seul commit. Je n'ai vu aucune référence à ce point sur les différentes pages d'informations.

J'ai _pull_ et _push_ sur la branche avec les changements que tu n'avais pas suggéré. Si j'ai manqué quelque chose, n'hésite pas à me le faire savoir.

Merci énormément à toi pour tous ces retours ! J'ai également hâte de voir cette branche sur **main** ! :star:

2023-06-01 07:46 UTC, tdd commented
Coucou @nina-alin ! 👋🏻

> Pour la partie purement syntaxique, concernant la tournure des phrases, j'ai l'impression que ça s'apprend en faisant. Je vois pas mal de phrases qui me semblaient bien à l'écriture et aux relectures, et tes commentaires me font prendre conscience que j'étais parfois un peu à côté de la plaque 😅

Clairement avec le temps. Il y a une histoire de cohérence de ton avec la partie concernée (Learn, Reference, etc.) et de fluidité du résultat, car une trad trop mot-à-mot ou trop proche de la syntaxe EN est parfois ampoulée en FR.

Lorsqu'on a traduit tout récemment, la relecture n'est pas assez objective ; dans l'idéal, on laisse passer quelques heures voire 1j avant de relire avec "des yeux neufs", ce qui entraîne souvent quelques reformulations.

Évidemment, si on n'est pas 100% au clair sur la sémantique d'origine, ça n'aide pas 😉 

Mais c'est le jeu ! Et ça s'améliore nettement avec l'expérience.

> Je t'ai laissé deux issues non _resolved_ avec deux points qui m'ont posé question. J'ai tout de même _commit_ les changements concernés, car je n'étais pas fondamentalement en désaccord avec toi sur ces points 😉

OK, je vais regarder ça.

> J'ai conscience d'avoir pris un morceau assez compliqué dès le début. En général, dans des domaines que je ne connais pas, je met toujours la barre assez haute, d'où le choix de `useDeferredValue` 😉 . C'est ce qui me permet réellement d'apprendre. Mais du coup, tu as du prendre pas mal de temps à tout corriger. Si pour la prochaine traduction, tu préfères que je prenne un fichier moins complexe à traduire, fais-le moi savoir.

Que nenni, c'est à toi de voir ce qui te parle le plus. Du moment que tu prends en compte le maximum de retours de review d'une trad à l'autre, tu vas progresser très vite.

Si je voulais y passer le moins de temps possible, je ferais toutes les trads moi-même, mais le but ici, comme pour la) première édition des docs, c'est d'aider à "former des traducteurs tech", à faire monter les gens en compétence pour qu'ils·elles puissent contribuer efficacement par la suite ici comme ailleurs. Ça me prend 5 à 10 fois plus de temps, mais c'est mon choix !

> Egalement, j'avais une question concernant l'historique des commits : est-ce que tu veux que j'_amend_ mes commits afin d'avoir un historique un maximum clair, ou vous ne prêtez pas spécialement attention à ce point ? Comme tu peux voir, je n'ai pas poussé ma traduction en un seul commit. Je n'ai vu aucune référence à ce point sur les différentes pages d'informations.

L'histo initial de ta branche est sans importance, du moment qu'il reste linéaire. En tous les cas, au moment de la finalisation, je le *rebase* sur le `main` à jour et je fais un dernier commit suite à la passe finale de revue visuelle et typographique.

Du moment que le titre de la PR est normalisé (ce qui impacte les messages de commit autour de la fusion côté GitHub), tout roule.

2023-06-01 07:48 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +- Des composants de Lazy-loading (*chargement fainéant, NdT*) avec [`lazy`](/reference/react/lazy)
Ici y'avait glissement sémantique : ce ne sont pas les composants qui font du lazy loading, on parle du fait de charger à la demande les composants (en utilisant `React.lazy` en l'occurrence). Par ailleurs, on a une trad FR établie ("chargement à la demande"), donc pas besoin de garder "lazy loading".

2023-06-01 07:49 UTC, tdd commented on src/content/reference/react/useDeferredValue.md
> +#### Comment délayer une valeur fonctionne-t-il en sous-jacent ? {/*how-does-deferring-a-value-work-under-the-hood*/}
Tiens, qu'est-ce qui te gênait ici ? "Sous le capot" est la trad établie (et littérale) de "under the hood", et on l'utilise régulièrement dans ces docs (y compris l'édition précédente).

2023-06-01 07:50 UTC, tdd approved these changes

2023-06-01 08:51 UTC, merged