Translation of the “createContext” page
reactjs/fr.react.dev pull request #489
Opened 2023-06-01 16:40 UTC by adevinwild

2023-06-02 21:40 UTC, tdd requested changes
Salut @adevinwild !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Écoute c'est pas mal du tout sur la prose, les corrections sont surtout de la fluidification, de la terminologie (ex. "fournisseur de contexte", "fournir") et un peu de typographie.

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/apis.md
> +title: "APIs React intégrées"
```suggestion
title: "API React intégrées"
```

Les acronymes ne sont pas accordés en français.

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/apis.md
> +En plus des [Hooks](/reference/react) et des [Composants](/reference/react/components), le package `react` propose également d'autres API utiles pour la définition des composants. Cette page répertor
```suggestion
En plus des [Hooks](/reference/react) et des [composants](/reference/react/components), le module `react` exporte également d'autres API utiles pour la définition des composants. Cette page répertorie toutes les autres API React modernes.
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/apis.md
> +- [`memo`](/reference/react/memo) permet à votre composant de sauter les réaffichages avec les mêmes props. Utilisé conjointement avec [`useMemo`](/reference/react/useMemo) et [`useCallback`](/refere
```suggestion
- [`memo`](/reference/react/memo) permet à votre composant dd'éviter de recalculer son rendu quand ses props n'ont pas changé. Utilisé conjointement avec [`useMemo`](/reference/react/useMemo) et [`useCallback`](/reference/react/useCallback).
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +[Voir d'autres exemples ci-dessous.](#usage)
```suggestion
[Voir d'autres exemples ci-dessous](#usage).
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +`createContext` vous permet de créer un [contexte](/learn/passing-data-deeply-with-context) que les composants peuvent partager ou lire.
```suggestion
`createContext` vous permet de créer un [contexte](/learn/passing-data-deeply-with-context) que des composants peuvent fournir ou lire.
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Utilisez `createContext` en dehors de tout composant afin de créer un contexte.
```suggestion
Appelez `createContext` en dehors de tout composant afin de créer un contexte.
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +* `defaultValue` : Ce sera la valeur uniquement utilisé lorsqu'il n'y a pas de contexte correspondant au-dessus du composant qui lit le contexte. Si vous n'avez pas de valeur par défaut, spécifiez `n
```suggestion
* `defaultValue` : la valeur utilisée lorsqu'il n'y a pas de contexte adapté fourni au-dessus du composant qui lit ce contexte. Si vous n'avez pas de valeur par défaut appropriée, indiquez `null`. La valeur par défaut est vue comme un « dernier recours ». Elle est statique et ne change jamais au fil du temps.
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +#### Retours {/*returns*/}
```suggestion
#### Valeur renvoyée {/*returns*/}
```

Trad établie.

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +`createContext` retourne un objet représentant le context.
```suggestion
`createContext` renvoie un objet représentant le contexte.
```

"Retourner" est une notions spatiale (cf. Glossaire)

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +**L'objet contexte lui-même ne contient aucune information.** Il représente _le_ contexte que les autres composants lisent ou partagent. Typiquement, vous utiliserez [`SomeContext.Provider`](#provide
```suggestion
**L'objet contexte lui-même ne contient aucune information.** Il représente _quel_ contexte les autres composants lisent ou fournissent. Vous utiliserez habituellement [`SomeContext.Provider`](#provider) dans les composants au-dessus afin de spécifier la valeur du contexte, et vous appellerez [`useContext(SomeContext)`](/reference/react/useContext) dans les composants en-dessous afin de lire cette valeur. L'objet contexte a quelques propriétés :
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +* `SomeContext.Consumer` est une alternative et une manière rarement utilisée afin de lire la valeur d'un contexte.
```suggestion
* `SomeContext.Consumer` est une façon alternative rarement utilisée de lire la valeur du contexte.
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Enveloppez vos composants dans un Provider afin de répartir sa valeur pour tous les composants à l'intérieur :
```suggestion
Enveloppez vos composants dans un fournisseur de contexte afin de définir la valeur de ce contexte pour tous les composants enveloppés :
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +* `value`: La valeur que vous souhaitez passer à tous les composants lisant ce contexte à l'intérieur d'un Provider, peu importe la profondeur. La valeur du contexte peut être de n'importe quel type.
```suggestion
* `value`: la valeur que vous souhaitez passer à tous les composants lisant ce contexte à l'intérieur de ce fournisseur, à quelque profondeur que ce soit. La valeur du contexte peut être de n'importe quel type. Un composant appelant [`useContext(SomeContext)`](/reference/react/useContext) à l'intérieur d'un fournisseur de contexte reçoit la `value` du fournisseur correspondant le plus proche en amont.
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Avant l'existence de `useContext`, il existait une ancienne méthode pour lire un contexte :
```suggestion
Avant l'arrivée de `useContext`, il existait une ancienne façon de lire un contexte :
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +  // 🟡 Ancienne méthode (non recommandée)
```suggestion
  // 🟡 Ancienne méthode (déconseillée)
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +* `children`: Une fonction. React appelle cette fonction avec la valeur du contexte actuel, déterminée par le même algorithme que `useContext()`, puis affiche le résultat retourné par cette fonction.
```suggestion
* `children` : une fonction. React appellera cette fonction avec la valeur du contexte actuel, déterminée par le même algorithme que pour `useContext()`, puis affichera le résultat renvoyé par cette fonction. De plus, chaque fois que le contexte des composants parents changera, React réexécutera cette fonction et mettra à jour l'interface utilisateur en conséquence.
```

Concordance des temps avec le futur après "when" qui est un présent narratif en anglais ; nous, on utilisera un futur simple.

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Par défaut, les valeurs reçues seront les <CodeStep step={3}>valeurs par défaut</CodeStep> que vous avez spécifiées lors de la création des contextes. Cependant, ça n'est pas utile car les valeurs pa
```suggestion
Par défaut, les valeurs reçues seront les <CodeStep step={3}>valeurs par défaut</CodeStep> que vous avez spécifiées lors de la création des contextes. Cependant, ça n'est pas très utile en soi car les valeurs par défaut ne changent jamais.
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Le contexte est utile car vous avez la possibilité de **fournir des valeurs dynamiques supplémentaires à partir de vos composants :**
```suggestion
L'utilité du contexte réside dans la possibilité de **fournir des valeurs dynamiques supplémentaires à partir de vos composants** :
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
```suggestion
```

Ahem, oubli de retrait de la VO après trad.

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Maintenant, le composant `Page`, ainsi que tous les composants imbriqués, quel que soit leur niveau de profondeur, auront accès aux valeurs de contexte transmises. Si ces valeurs de contexte changent
```suggestion
Désormais, le composant `Page`, ainsi que tous les composants imbriqués, quel que soit leur niveau de profondeur, auront accès aux valeurs de contexte transmises. Si ces valeurs de contexte changent, React réexécutera les composants qui les lisent.
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +[Approfondissez vos connaissances sur la consommation et la création de contexte au travers d'exemples concrets.](/reference/react/useContext)
```suggestion
[Apprenez-en davantage sur la fourniture et la lecture de contexte au travers d'exemples concrets](/reference/react/useContext).
```

Trad établie

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +### Importation et exportation du contexte à partir d'un fichier {/*importing-and-exporting-context-from-a-file*/}
```suggestion
### Importer et exporter un contexte depuis un fichier {/*importing-and-exporting-context-from-a-file*/}
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Parfois, il est nécessaire que des composants présents dans différents fichiers puissent accéder au même contexte. C'est pourquoi il est courant de déclarer les contextes dans un fichier séparé. Ensu
```suggestion
Des composants auront souvent besoin d'accéder au même contexte depuis de multiples fichiers. C'est pourquoi il est courant de déclarer les contextes dans un fichier séparé. Vous pouvez alors utiliser [l'instruction `export`](https://developer.mozilla.org/fr/docs/web/javascript/reference/statements/export) pour rendre le contexte accessible par d'autres fichiers :
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
>  Components declared in other files can then use the [`import`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/import) statement to read or provide this context:
```suggestion
```

Et hop, deuxième.

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Ensuite, les composants déclarés dans d'autres fichiers peuvent utiliser l'instruction [`import`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/import) pour lire ou par
```suggestion
Les composants déclarés dans d'autres fichiers peuvent alors utiliser l'instruction [`import`](https://developer.mozilla.org/fr/docs/web/javascript/reference/statements/import) pour lire ou fournir ce contexte :
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Ça fonctionne de la même manière que [l'importation et l'exportation de composants.](/learn/importing-and-exporting-components)
```suggestion
Ça fonctionne de la même manière que [l'importation et l'exportation de composants](/learn/importing-and-exporting-components).
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +### Je ne trouve pas de moyen de modifier la valeur du contexte {/*i-cant-find-a-way-to-change-the-context-value*/}
```suggestion
### Je ne parviens pas à modifier la valeur du contexte {/*i-cant-find-a-way-to-change-the-context-value*/}
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Cette valeur ne change jamais. React utilise cette valeur uniquement comme une valeur de secours si aucun Provider correspondant n'est trouvé au-dessus.
```suggestion
Cette valeur ne change jamais. React utilise cette valeur uniquement comme une valeur de secours si aucun fournisseur correspondant n'est trouvé au-dessus du composant lecteur.
```

2023-06-02 21:40 UTC, tdd commented on src/content/reference/react/createContext.md
> +Pour mettre à jour le contexte au fil du temps, [intégrez un état et entourez vos composants avec un Provider.](/reference/react/useContext#updating-data-passed-via-context)
```suggestion
Pour mettre à jour le contexte au fil du temps, [intégrez un état local et enveloppez vos composants avec un fournisseur de contexte](/reference/react/useContext#updating-data-passed-via-context).
```

2023-06-03 05:04 UTC, adevinwild commented on src/content/reference/react/createContext.md
Aïe!
Désolé, je me mettais toujours les phrases en VO juste au dessus de ma traduction petit oubli de ma part ^^

2023-06-04 17:23 UTC, tdd approved these changes

2023-06-04 17:23 UTC, merged