translation of Passing Data Deeply with Context
reactjs/fr.react.dev pull request #493
Opened 2023-06-06 16:47 UTC by linsolas

Traduction française de la page [`Passing Data Deeply with Context`](https://react.dev/learn/passing-data-deeply-with-context).

2023-07-01 22:37 UTC, tdd requested changes
Salut @linsolas !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Désolé pour le lag, saturé en ce moment et en prime la plupart des trads en attente étaient des romans !

Bon au global excellent taf, des paragraphes entiers sans rien à dire, bravo.

Juste "faire remonter l'état" et "faire percoler les props", principalement, quelques détails de ponctuation finale quand même en grasses si c'est toute la phrase, ce genre de choses, rien de bien méchant.

Moins de mot à mot !

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +<Diagram name="passing_data_context_far" height={430} width={608} captionPosition="top" alt="Un diagramme avec un arbres à dix nœeuds, chacun ayant deux enfants ou moins. Le nœud parent à la racine c
```suggestion
<Diagram name="passing_data_context_far" height={430} width={608} captionPosition="top" alt="Un diagramme avec un arbres à dix nœeuds, chacun ayant deux enfants ou moins. Le nœud parent à la racine contient une bulle qui représente une valeur surlignée en orange. La valeur est projetée directement vers quatre nœuds feuilles et un composant intermédiaire de l'arbre, qui sont tous surlignés en orange. Aucun des autres composants intermédiaires n'est surligné.">
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Tout d'abord, vous devez créer le contexte. Vous avez besoin de **l'exporter depuis un fichier** pour que vos composants puissent l'utiliser :
```suggestion
Tout d'abord, il vous faut créer le contexte. Vous devrez **l'exporter depuis un fichier** pour que vos composants puissent l'utiliser :
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Pour le moment, le composant `Heading` lit `level` depuis le props :
```suggestion
Pour le moment, le composant `Heading` lit `level` depuis les props :
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Supprimez la prop `level`, et lisez plutôt la valeur depuis le contexte `LevelContext` que vous venez d'importer :
Reformulation parfaite, notamment le placement du "plutôt", bravo 👏

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +`useContext` est un Hook. Tout comme `useState` et `useReducer`, vous ne pouvez appeler un Hook qu'au début d'un composant React (et non pas dans des boucles ou des conditions). **`useContext` indiqu
```suggestion
`useContext` est un Hook. Tout comme `useState` et `useReducer`, vous ne pouvez appeler un Hook qu'au niveau racine d'un composant React (et non pas dans des boucles ou des conditions). **`useContext` indique à React que le composant `Heading` souhaite lire le `LevelContext`.**
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Pour rappel, voici le code que vous essayez de faire marcher :
J'aime bien le passage au présent de narration pour éviter un subjonctif imparfait moche sur "essayer".

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Remarquez que cet exemple ne fonctionne pas encore tout à fait. Tous les en-têtes ont le même niveau parce que **même si vous *utilisez* le contexte, vous ne l'avez pas encore *fourni***. React ne sa
```suggestion
Remarquez que cet exemple ne fonctionne pas encore tout à fait. Tous les en-têtes ont le même niveau parce que **même si vous *utilisez* le contexte, vous ne l'avez pas encore *fourni***. React ne sait pas où l'obtenir !
```

Putain, j'étais **persuadé** qu'en-tête était féminin, mais non, c'est bien masculin. TIL!

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Si vous ne fournissez pas le contexte, React utilisera les valeurs par défaut que vous avez spécifié dans l'étape précédente. Dans cet exemple, vous aviez spécifié `1` comme argument à `createContext
```suggestion
Si vous ne fournissez pas le contexte, React utilisera la valeur par défaut que vous avez spécifiée dans l'étape précédente. Dans cet exemple, vous aviez spécifié `1` comme argument à `createContext`, donc `useContext(LevelContext)` renvoie `1`, transformant tous ces en-têtes en `<h1>`. Corrigeons ce problème en demandant à chaque `Section` de fournir son propre contexte.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Le composant `Section` effectue actuellement le rendu de ses enfants ainsi :
```suggestion
Le composant `Section` effectue actuellement le rendu de ses enfants comme suit :
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Le résultat est le même qu'avec le code d'origine, mais vous n'avez pas eu besoin de transmettre la prop `level` à chaque composant `Heading`. Au lieu de ça, il « détermine » son niveau d'en-tête en
```suggestion
Le résultat est le même qu'avec le code d'origine, mais vous n'avez plus besoin de transmettre la prop `level` à chaque composant `Heading`. Au lieu de ça, il « détermine » son niveau d'en-tête en interrogeant la `Section` la plus proche :
```

Léger écart avec la VO mais plus lisible je trouve.

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Pour l'instant, vous devez toujours spécifier manuellement le `level` de chaque section :
```suggestion
À ce stade, vous devez quand même spécifier manuellement le `level` de chaque section :
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Puisque le contexte vous permet de lire une information à partir d'un composant plus haut, chaque `Section` pourrait lire le `level` de la `Section` supérieure, puis transmettre automatiquement `leve
```suggestion
Puisque le contexte vous permet de lire une information à partir d'un composant plus haut, chaque `Section` pourrait lire le `level` de la `Section` supérieure, puis transmettre automatiquement `level + 1` en dessous d'elle. Voici comment faire :
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Cet exemple utilise des niveaux d'en-têtes parce qu'ils montrent visuellement à quel point les composants imbriqués peuvent surcharger le contexte. Mais le contexte est aussi utile dans bien d'autres
```suggestion
Cet exemple utilise des niveaux d'en-têtes parce qu'ils montrent visuellement comment des composants imbriqués peuvent surcharger le contexte. Mais le contexte est tout aussi utile dans bien d'autres cas. Vous pouvez transmettre n'importe quelle information nécessaire à tout le sous-arbre : le thème de couleurs actif, l'utilisateur connecté, et ainsi de suite.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +## Le contexte passe par des composants intermédiaires {/*context-passes-through-intermediate-components*/}
```suggestion
## Le contexte traverse les composants intermédiaires {/*context-passes-through-intermediate-components*/}
```

Léger glissement sémantique

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Vous pouvez insérer autant de composants que vous voulez entre le composant qui fournit le contexte et celui qui l'utilise. Ça inclut aussi bien les composants intégrés comme `<div>` que ceux que vou
```suggestion
Vous pouvez insérer autant de composants que vous voulez entre le composant qui fournit le contexte et celui qui l'utilise. Ça inclut aussi bien les composants natifs comme `<div>` que ceux que vous pourriez créer vous-même.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +        body="J'ai adoré !"
👍

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Vous n'avez rien eu à faire pour que ça marche. Une `Section` spécifie le contexte pour l'arbre qu'elle contient, vous pouvez donc y insérer un `<Heading>` n'importe où et il aura une taille correcte
```suggestion
Vous n'avez rien eu à faire pour que ça marche. Une `Section` spécifie le contexte pour l'arbre qu'elle contient, vous pouvez donc y insérer un `<Heading>` n'importe où et il aura le niveau correct. Essayez donc dans le bac à sable ci-dessus.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +La façon dont les contextes fonctionnent peut vous rappeler [l'héritage des propriétés CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance). En CSS, vous pouvez spécifier `color: blue`
```suggestion
La façon dont les contextes fonctionnent peut vous rappeler [l'héritage des valeurs de propriétés en CSS](https://developer.mozilla.org/fr/docs/Web/CSS/inheritance). En CSS, vous pouvez spécifier `color: blue` pour un `<div>` et n'importe quel nœud du DOM qu'il contient, aussi profond soit-il, héritera de cette couleur, à moins qu'un nœud intermédiaire ne surcharge ça avec `color: green`. C'est pareil avec React : la seule façon de surcharger un contexte venant d'en haut est d'enrober les enfants dans un fournisseur de contexte avec une valeur différente.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +En CSS, des propriétés distinctes comme `color` et `background-color` ne sont pas remplacées les unes par les autres. Vous pouvez définir la `color` de toutes les `<div>` en rouge sans impacter le `b
```suggestion
En CSS, des propriétés distinctes comme `color` et `background-color` ne sont pas remplacées les unes par les autres. Vous pouvez définir la `color` de toutes les `<div>` en rouge sans impacter la `background-color`. De la même façon, **des contextes React distincts ne s'écrasent pas les uns les autres**. Chaque contexte que vous créez avec `createContext()` est complétement isolé des autres et lie les composants qui utilisent et fournissent ce contexte *particulier*. Un composant peut utiliser et fournir différents contextes sans problème.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Il est très tentant d'utiliser des contextes ! Toutefois, il est aussi très facile d'en abuser. **Ce n'est pas parce que vous devez descendre des props sur plusieurs niveaux que vous devez mettre ces
```suggestion
Il est très tentant d'utiliser des contextes ! Toutefois, il est aussi très facile d'en abuser. **Ce n'est pas parce que vous devez propager des props sur plusieurs niveaux que vous devez mettre ces informations dans un contexte**.
```

Quasi parfait 😉

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +2. **Extrayez des composants et [passez-leur du JSX dans les `children`](/learn/passing-props-to-a-component#passing-jsx-as-children)**. Si vous passez des données à travers plusieurs couches de comp
```suggestion
1. **Commencez par [passer les props](/learn/passing-props-to-a-component).** Si vos composants ne sont pas triviaux, il est courant de passer une douzaine de props à travers une douzaine de composants. Ça peut sembler fastidieux, mais ça permet de savoir clairement quels composants utilisent quelles données ! La personne chargée de la maintenance de votre code sera ravie que vous ayez rendu le flux de données explicite grâce aux props.
2. **Extrayez des composants et [passez-leur du JSX dans les `children`](/learn/passing-props-to-a-component#passing-jsx-as-children).** Si vous passez des données à travers plusieurs couches de composants qui ne les utilisent pas (et ne font que les transmettre plus bas), ça signifie souvent que vous avez oublié d'extraire certains composants en cours de route. Par exemple, vous pouvez passer certaines données en props comme `posts` à des composants visuels qui ne les utilisent pas directement, tel que `<Layout posts={posts} />`. Préférez faire en sorte que `Layout` prenne `children` en tant que prop, puis faites le rendu de `<Layout><Posts posts={posts} /></Layout>`. Ça réduit le nombre de couches entre les composants qui spécifient la donnée et ceux qui l'utilisent.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Si aucune de ces approches ne vous convient, envisagez le contexte.
```suggestion
Si aucune de ces approches ne vous convient, envisagez un contexte.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +## Cas d'utilisation du contexte {/*use-cases-for-context*/}
```suggestion
## Cas d'utilisation des contextes {/*use-cases-for-context*/}
```

Insistons sur le fait qu'il en existe plusieurs, tous cloisonnés.

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +* **Routage :** la plupart des solutions de routage utilise un contexte en interne pour conserver la route actuelle. C'est ainsi que chaque lien « sait » s'il est actif ou non. Si vous construisez vo
```suggestion
* **Routage :** la plupart des solutions de routage utilise un contexte en interne pour conserver la route actuelle. C'est ainsi que chaque lien « sait » s'il est actif ou non. Si vous construisez votre propre routeur, vous serez peut-être tenté·e de faire de même.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +* **Gestion d'état :** au fur et à mesure que votre appli grandit, vous pouvez vous retrouver avec de nombreux états proches de la racine de votre appli. De nombreux composants distants pourraient vo
```suggestion
* **Gestion d'état :** au fur et à mesure que votre appli grandit, vous pouvez vous retrouver avec de nombreux états proches de la racine de votre appli. De nombreux composants distants pourraient vouloir les changer. Il est courant [d'utiliser un réducteur avec un contexte](/learn/scaling-up-with-reducer-and-context) pour gérer des états complexes et les transmettre à des composants distants sans trop galérer.
```

"problèmes" est trop négatif et semble parler de bugs. Si "galérer" te semble vraiment trop familier, "sans trop de cérémonie" est une bonne alternative.

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  1. Créez et exportez-le avec `export const MyContext = createContext(defaultValue)`.
```suggestion
  1. Créez-le et exportez-le avec `export const MyContext = createContext(defaultValue)`.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  2. Passez-le au Hook `useContext(MyContext)` pour que n'importe quel composant enfant puisse le lire, aussi distant soit-il.
```suggestion
  2. Passez-le au Hook `useContext(MyContext)` depuis n'importe quel composant enfant pour pouvoir le lire, aussi profondément imbriqué soit-il.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Pour l'instant, `App` transmet `imageSize` à `List`, qui la transmet ensuite à chaque `Place` qui transmettent enfin à `PlaceImage`. Supprimez la prop `imageSize`, et donnez-la directement à `PlaceIm
```suggestion
Pour l'instant, `App` transmet `imageSize` à `List`, qui la transmet ensuite à chaque `Place` qui transmettent enfin à `PlaceImage`. Supprimez la prop `imageSize` pour la fournir directement à `PlaceImage` depuis le composant `App`.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  description: 'la tradition de choisir des couleurs vives pour les maisons a commencé à la fin du XXe siècle.',
```suggestion
  description: 'La tradition de choisir des couleurs vives pour les maisons remonte à la fin du XXe siècle.',
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  description: 'pour sauver les maisons de la démolition, Huang Yung-Fu, un résident de la région, a peint 1200 maisons en 1924.',
```suggestion
  description: 'pour sauver les maisons de la démolition, Huang Yung-Fu, un résident de la région, a peint l'ensemble des 1 200 maisons en 1924.',
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  description: "l'une des plus grandes peintures murales du monde recouvre les maisons d'un quartier à flanc de colline.",
```suggestion
  description: "L'une des plus grandes fresques murales du monde recouvre les maisons d'un quartier à flanc de colline.",
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  description: 'ce monument a été créé par Jorge Selarón, un artiste chilien, en guise d’« hommage au people du Brésil ».',
```suggestion
  description: 'Ce monument a été créé par Jorge Selarón, un artiste d'origine chilienne, en guise d’« hommage au people du Brésil ».',
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  description: 'les maisons sont peintes selon un système de couleurs spécifique datant du XIVe siècle.',
```suggestion
  description: 'Les maisons sont peintes selon un système de couleurs spécifique datant du XVIe siècle.',
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  description: "plusieurs théories expliquent pourquoi les maisons sont peintes en bleu, notamment parce que cette couleur repousse les moustiques ou qu'elle symbolise le ciel et le paradis.",
```suggestion
  description: "Plusieurs théories expliquent pourquoi les maisons sont peintes en bleu, notamment parce que cette couleur repousserait les moustiques ou qu'elle symboliserait le ciel et le paradis.",
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  description: 'en 2009, le village a été converti en centre culturel en peignant les maisons et en accueillant des exhibitions et des installations artistiques.',
```suggestion
  description: 'En 2009, le village a été converti en carrefour culturel en peignant les maisons et en accueillant des expositions et des installations artistiques.',
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Supprimez la prop `imageSize` de tous les composants.
```suggestion
Retirez la prop `imageSize` de tous les composants.
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Créez et exportez `ImageSizeContext` depuis `Context.js`. Ensuite, enrobez la `List` dans `<ImageSizeContext.Provider value={imageSize}>` pour faire descendre la valeur, puis `useContext(ImageSizeCon
```suggestion
Créez et exportez `ImageSizeContext` depuis `Context.js`. Ensuite, enrobez la `List` dans `<ImageSizeContext.Provider value={imageSize}>` pour propager la valeur vers le bas, puis `useContext(ImageSizeContext)` pour la lire dans `PlaceImage` :
```

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +  description: 'la tradition de choisir des couleurs vives pour les maisons a commencé à la fin du XXe siècle.',
Merci de reporter ici et plus bas les ajustements de trads pour les légendes ! 😁

2023-07-01 22:37 UTC, tdd commented on src/content/learn/passing-data-deeply-with-context.md
> +Remarquez comment les composants intermédiaires n'ont plus besoin de transmettre `imageSize`.
```suggestion
Remarquez comme les composants intermédiaires n'ont plus besoin de transmettre `imageSize`.
```

2023-07-01 22:37 UTC, tdd requested changes
Salut @linsolas !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Désolé pour le lag, saturé en ce moment et en prime la plupart des trads en attente étaient des romans !

Bon au global excellent taf, des paragraphes entiers sans rien à dire, bravo.

Juste "faire remonter l'état" et "faire percoler les props", principalement, quelques détails de ponctuation finale quand même en grasses si c'est toute la phrase, ce genre de choses, rien de bien méchant.

Moins de mot à mot !

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-02 16:16 UTC, linsolas commented on src/content/learn/passing-data-deeply-with-context.md
> +Remarquez que cet exemple ne fonctionne pas encore tout à fait. Tous les en-têtes ont le même niveau parce que **même si vous *utilisez* le contexte, vous ne l'avez pas encore *fourni***. React ne sa
Je dois dire que je le savais, sans être persuadé. J'avais fait la vérification.

2023-07-02 16:33 UTC, linsolas commented on src/content/learn/passing-data-deeply-with-context.md
> +  description: 'la tradition de choisir des couleurs vives pour les maisons a commencé à la fin du XXe siècle.',
Fait. J'ai aussi changer des `'`en `"` là où il fallait.

2023-07-04 10:06 UTC, tdd approved these changes

2023-07-04 10:09 UTC, merged