Translation of the “Importing and Exporting Components” page
reactjs/fr.react.dev pull request #494
Opened 2023-06-08 19:08 UTC by YannBirba

Traduction française de la page [Importing and Exporting Components](https://react.dev/learn/importing-and-exporting-components).

2023-06-12 11:49 UTC, tdd requested changes
Salut @YannBirba !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

C'est pas mal du tout, notamment les restructurations pour la fluidité plutôt que de trop rester dans le mot-à-mot. Tu restes sur "cela" au lieu de "ça" (cf. Meilleures Pratiques) et ça sent la fatigue sur la fin (nombre de 2e personnes du pluriel remplacées par des infinitifs), mais franchement c'est bien, surtout pour un début !

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-06-12 11:49 UTC, tdd commented on src/content/learn/importing-and-exporting-components.md
> +Actuellement, `Gallery.js` exporte à la fois `Profile` et `Gallery`, ce qui est un peu confus.
```suggestion
Pour le moment, `Gallery.js` exporte à la fois `Profile` et `Gallery`, ce qui est un peu déroutant.
```

"Actuellement" est juste, mais dans le contexte de l'exo (qui veut faire évoluer ça), "pour le moment" est plus pertinent / introductif.

2023-06-12 11:49 UTC, tdd commented on src/content/learn/importing-and-exporting-components.md
> +Vous devrier utiliser soit un export par défaut, soit un export nommé pour le composant `Profile`, mais assurez-vous d’utiliser la syntaxe d’importation correspondante dans `App.js` et `Gallery.js` !
```suggestion
Vous pouvez utiliser soit un export par défaut, soit un export nommé pour le composant `Profile`, mais assurez-vous d’utiliser la syntaxe d’importation correspondante dans `App.js` et `Gallery.js` ! N'hésitez pas à vous référer au tableau de la partie « En détail » vue plus tôt :
```

2023-06-12 11:49 UTC, tdd commented on src/content/learn/importing-and-exporting-components.md
> +| Syntaxe           | Déclaration d’exportation                           | Déclaration d’importation                          |
```suggestion
| Syntaxe           | Déclaration d’export                           | Déclaration d’import                          |
```

2023-06-12 11:49 UTC, tdd commented on src/content/learn/importing-and-exporting-components.md
> +N’oublier pas d’importer vos composants là où ils sont appelés. `Gallery` n’utilise-t-il pas aussi `Profile` ?
```suggestion
N’oubliez pas d’importer vos composants là où ils sont appelés. `Gallery` n’utilise-t-il pas lui aussi `Profile` ?
```

2023-06-12 17:43 UTC, YannBirba commented on src/content/learn/importing-and-exporting-components.md
> +## Exporter et importer un composant{/*exporting-and-importing-a-component*/}
Yes effectivement 👍

2023-06-15 19:45 UTC, YannBirba commented on src/content/learn/importing-and-exporting-components.md
> +2. **Exporter** votre fonction composant de ce fichier (en utilisant soit les exports [par défaut](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/export#using_the_default_e
Effectivement, merci de la remarque !

2023-06-15 19:49 UTC, YannBirba commented on src/content/learn/importing-and-exporting-components.md
> +#### Les Exports par défaut versus les exports nommés {/*default-vs-named-exports*/}
C'est noté

2023-06-15 20:27 UTC, YannBirba commented
Je viens de finir de review, merci beaucoup pour toutes les explications, les tips et les conseils !

2023-06-19 11:48 UTC, merged