Translation of the “Updating Objects in State” page
reactjs/fr.react.dev pull request #495
Opened 2023-06-08 22:10 UTC by LaureRC

Traduction française de la page [Updating Objects in State](https://react.dev/learn/updating-objects-in-state).

2023-06-20 10:47 UTC, tdd commented
Coucou @LaureRC tu as fini le taf ou pas ? C'est encore en Draft…

2023-07-01 22:38 UTC, tdd commented
@LaureRC nouveau ping : tu as fini ou pas ? Si oui marque-la "Ready for review" en bas de discussion stp

2023-07-02 16:54 UTC, LaureRC commented
Bonjour @tdd ! Désolée pour le long délai de réponse, malheureusement j'ai été très occupée (lorsque je me suis proposée tout était bon, mais le travail et le perso m'ont très vite rattrapée !). Je me charge de mettre ça en review tout de suite !

2023-07-04 12:47 UTC, tdd requested changes
Salut @LaureRC !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Comme toujours, très bon boulot. On sent un recalage de certaines habitudes à mi-chemin, entre ta première passe et la dernière je suppose.

Quelques tweaks de formulation notamment, et quelques modifs que je n'ai pas reportées sur toutes les occurrences (mais je t'ai demandé de le faire dans mes commentaires).

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +Ou, écrit en une seule instruction :
```suggestion
En une seule instruction, ça donnerait ceci :
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +  ...person, // Copiez les autres champs
```suggestion
  ...person, // Copie les autres champs
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +Si vous modifiez `obj3.artwork.city`, ça affectera à la fois `obj2.artwork.city` et `obj1.city`. C’est parce que `obj3.artwork`, `obj2.artwork` et `obj1` sont le même objet. C’est difficile à voir si
```suggestion
Si vous modifiiez `obj3.artwork.city`, ça affecterait à la fois `obj2.artwork.city` et `obj1.city`. C’est parce qu'`obj3.artwork`, `obj2.artwork` et `obj1` sont le même objet. C’est difficile à percevoir quand on considère les objets comme « imbriqués ». Il s’agit plutôt d’objets distincts qui « pointent » les uns vers les autres à l’aide de propriétés.
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +Le `draft` fourni par Immer est un type spécial d’objet, appelé [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), qui « enregistre » ce que vous faites
```suggestion
Le `draft` fourni par Immer est un type spécial d’objet, appelé [Proxy](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Proxy), qui « enregistre » ce que vous faites avec. C’est pourquoi vous pouvez le modifier autant que vous le souhaitez ! Sous le capot, Immer détermine quelles parties du `draft` ont été modifiées et produit un tout nouvel objet qui contient vos modifications.
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +2. Remplacer `import { useState } from 'react'` par `import { useImmer } from 'use-immer'`.
```suggestion
1. Exécutez `npm install use-immer` pour ajouter Immer en tant que dépendance
2. Remplacez alors `import { useState } from 'react'` par `import { useImmer } from 'use-immer'`.
```

Instructions, donc impératif.

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +Remarquez à quel point les gestionnaires d’événements sont devenus plus concis. Vous pouvez mélanger et combiner `useState` et `useImmer` dans un seul composant autant que vous le souhaitez. Immer es
👍

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +#### Pourquoi la mutation de l’état n’est pas recommandée dans React ? {/*why-is-mutating-state-not-recommended-in-react*/}
```suggestion
#### Pourquoi déconseiller la mutation d’état dans React ? {/*why-is-mutating-state-not-recommended-in-react*/}
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +* **Débogage :** Si vous utilisez `console.log` et que vous ne mutez pas l’état, vos anciens logs ne seront pas écrasés par les changements d’état les plus récents. Vous pouvez donc voir clairement c
```suggestion
* **Débogage :** si vous utilisez `console.log` et que vous ne mutez pas l’état, vos anciens logs ne seront pas écrasés par les changements d’état plus récents. Vous pouvez donc voir clairement comment l’état a changé entre les rendus.
```

Pas de majuscules derrière les deux-points en FR.

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +* **Optimisations :** Les [stratégies d’optimisation](/reference/react/memo) courantes de React reposent sur la possibilité de sauter des étapes si les propriétés ou l’état précédents sont identiques
```suggestion
* **Optimisations :** les [stratégies d’optimisation](/reference/react/memo) courantes de React reposent sur la possibilité de sauter des étapes si les propriétés ou l’état précédents sont identiques aux suivants. Si vous ne modifiez jamais l’état, vérifier s’il y a eu des changements peut être très rapide. Si `prevObj === obj`, vous pouvez être certain·e qu’aucun changement n’a pu se produire à l’intérieur de celui-ci.
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +* **Implémentation plus simple :** Puisque React ne repose pas sur la mutation, il n’a pas besoin de faire quoi que ce soit de spécial avec vos objets. Il n’a pas besoin de trafiquer leurs propriétés
```suggestion
* **Nouvelles fonctionnalités :** les nouvelles fonctionnalités de React que nous développons reposent sur le fait que l’état est [traité comme un instantané](/learn/state-as-a-snapshot). Si vous modifiez des versions précédentes de l’état, ça peut vous empêcher d’utiliser les nouvelles fonctionnalités.
* **Changements de besoin :** certaines fonctionnalités d’application, comme l’implémentation d’actions pour annuler/rétablir, l’affichage d’un historique des modifications ou la possibilité de réinitialiser un formulaire à des valeurs antérieures, sont plus faciles à réaliser lorsque rien n’est modifié. Ceci est dû au fait que vous pouvez conserver en mémoire des copies passées de l’état et les réutiliser lorsque c’est pertinent. Si vous adoptez une approche modifiante dès le départ, il peut être difficile d’ajouter ultérieurement ce type de fonctionnalités.
* **Implémentation simplifiée :** puisque React ne repose pas sur la mutation, il n’a pas besoin de faire quoi que ce soit de spécial avec vos objets. Il n’a pas besoin de trafiquer leurs propriétés, de toujours les envelopper dans des proxies ou de réaliser d’autres actions à l’initialisation, comme le font de nombreuses solutions « réactives ». C’est également la raison pour laquelle React vous permet de mettre n’importe quel objet dans l’état, quelle que soit sa taille, sans problèmes de performances ou d’exactitude.
```

Bien joué pour "trafiquer", et d'une façon générale pour la trad.

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +* Vous pouvez utiliser la syntaxe de décomposition d’objet `{...obj, something: 'newValue'}` pour créer des copies d’objets.
```suggestion
* Vous pouvez utiliser la syntaxe de *spread* d’objet `{...obj, something: 'newValue'}` pour créer des copies d’objets.
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +#### Trouver et corriger la mutation {/*find-and-fix-the-mutation*/}
```suggestion
#### Repérer et corriger la mutation {/*find-and-fix-the-mutation*/}
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +Le problème était dans la mutation à l’intérieur de `handleMove`. Elle modifiait `shape.position`, mais il s’agit du même objet que celui pointé par `initialPosition`. C’est pourquoi la forme et l’ar
```suggestion
Le problème était dans la mutation à l’intérieur de `handleMove`. Elle modifiait `shape.position`, mais il s’agit du même objet que celui pointé par `initialPosition`. C’est pourquoi la forme et l’arrière-plan se déplacent tous les deux. (C’est une mutation, donc le changement ne se reflète à l’écran que lorsqu’une mise à jour non liée — le changement de couleur — déclenche un nouveau rendu.)
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +La solution consiste à supprimer la mutation de `handleMove` et à utiliser la syntaxe de décomposition pour copier la forme. Notez que `+=` est une mutation, vous devez donc la réécrire en utilisant
```suggestion
La solution consiste à retirer la mutation de `handleMove` et à utiliser la syntaxe de *spread* pour copier la forme. Notez que `+=` est une mutation, vous devez donc la réécrire en utilisant une opération `+` classique.
```

2023-07-04 12:47 UTC, tdd commented on src/content/learn/updating-objects-in-state.md
> +Il s’agit du même exemple comportant des bugs que dans l’exercice précédent. Cette fois, corrigez la mutation en utilisant Immer. Pour vous faciliter la tâche, `useImmer` est déjà importé, vous devez
```suggestion
Il s’agit du même exemple défectueux que dans l’exercice précédent. Cette fois-ci, corrigez la mutation en utilisant Immer. Pour vous faciliter la tâche, `useImmer` est déjà importé, vous devez donc modifier la variable d’état `shape` pour l’utiliser.
```

2023-07-04 12:47 UTC, tdd requested changes
Salut @LaureRC !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Comme toujours, très bon boulot. On sent un recalage de certaines habitudes à mi-chemin, entre ta première passe et la dernière je suppose.

Quelques tweaks de formulation notamment, et quelques modifs que je n'ai pas reportées sur toutes les occurrences (mais je t'ai demandé de le faire dans mes commentaires).

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-05 17:14 UTC, LaureRC commented
Hello @tdd ! Merci pour cette review très détaillée, je n'avais pas de retours particuliers dessus donc j'ai intégré tous tes retours en un seul commit comme demandé puis j'ai ajouté un dernier commit pour gérer les dernières occurrences de soucis que tu avais mentionné dans ta review!

Merci pour les retours positifs également, malgré le très long délai pour passer en "ready" (encore désolée pour ça) je m'étais quand même bien appliquée à suivre les consignes des bonnes pratiques et du glossaire (même si certaines ont quand même réussi à m'échapper!). Par contre je me suis faite avoir à penser devoir mettre partout les bonnes apostrophes typographiques, je saurais pour la prochaine fois que ça n'est nécessaire que dans le code! Il faudrait peut-être adapter le paragraphe concernant les apostrophes dans le document des bonnes pratiques du coup pour le préciser.

Je n'ai d'ailleurs pas traité les apostrophes qui ont été modifiées dans tes retours, ce n'est pas tout à fait homogène donc, dis moi si tu veux que je refasse une passe là-dessus, mais j'imagine que tu t'en occuperas pendant ta passe finale? Autrement tout devrait donc être bon! Fais moi signe si j'ai oublié quelque chose, je m'assurerai de réagir rapidement! 🙂

2023-07-06 08:21 UTC, tdd approved these changes

2023-07-06 08:25 UTC, merged

2023-07-06 10:23 UTC, tdd commented
Dis-moi @LaureRC souhaites-tu + peux-tu tout prochainement décliner ce taf pour "Updating Arrays in State", ou est-ce préférable que je m'en occupe ?

2023-07-06 12:11 UTC, tdd commented
Salut @LaureRC !

Écoute c'est pas **urgent** (je priorise les parties antérieures de Learn pour le moment), et du 21/07 au 15/08 je serai en congés et donc moins réactif, mais ça me semble être logique que tu t'en occupes si ça te va, vu que tu peux capitaliser sur ton travail pour la "version Objets". Je te l'affecte, du coup.