Extracting state logic into a reducer
reactjs/fr.react.dev pull request #497
Opened 2023-06-12 16:48 UTC by linsolas

Traduction de la page [Extracting State Logic into a Reducer](https://react.dev/learn/extracting-state-logic-into-a-reducer).

J'ai gardé le verbe *dispatcher* tel quel (mais en italique).

2023-07-02 14:53 UTC, tdd requested changes
Salut @linsolas !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Beau boulot comme d'habitude, même si on sent de-ci de-là la fatigue 😉 et que quelques choix de formulation sont améliorables.

**Il me reste les Défis à revoir**, mais voici déjà la partie principale.

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Le Hook `useReducer` est similaire à `useState` — vous devez lui passer un état initial and il renvoie une valeur d'état et un moyen de le redéfinir (dans ce cas, la fonction de *dispatch*). Toutefoi
```suggestion
Le Hook `useReducer` est similaire à `useState` : d'une part vous devez lui passer un état initial, d'autre part il renvoie une valeur d'état ainsi qu'un moyen de le redéfinir (en l'occurrence, la fonction de *dispatch*). Toutefois, des différences existent.
```

Pas mal de hiatus à lisser, du coup…

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +et renvoie :
```suggestion
Il renvoie :
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +1. Un valeur d'état.
```suggestion
1. Une valeur d'état.
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +2. Un fonction *dispatch* (pour « *dispatcher* » les actions de l'utilisateur vers le réducteur).
```suggestion
2. Une fonction *dispatch* (pour « *dispatcher* » les actions de l'utilisateur vers le réducteur).
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> -Now it's fully wired up! Here, the reducer is declared at the bottom of the component file:
Argh, tu as purement et simplement viré la ligne !

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +  {id: 0, text: 'Visiter le musée de Kafka', done: true},
Bon en gros change partout, idem pour la photo du mur John Lennon…

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +        <button onClick={() => setIsEditing(true)}>Éditer</button>
```suggestion
        <button onClick={() => setIsEditing(true)}>Modifier</button>
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +- **Taille du code** : avec un `useState`, vous devez généralement écrire moins de code au début. Avec `useReducer`, vous devez écrire à la fois la fonction de réduction _et_ les actions de *dispatch
```suggestion
- **Taille du code** : avec un `useState`, vous devez généralement écrire moins de code au début. Avec `useReducer`, vous devez écrire à la fois la fonction de réduction _et_ *dispatcher* les actions. Cependant, `useReducer` peut aider à réduire le code si plusieurs gestionnaires d'événements modifient l'état de façon similaire.
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +- **Lisibilité** : `useState` est très facile à lire lorsque les mises à jour d'état sont simples. Quand ça se complique, elles peuvent gonfler le code de votre composant et le rendre difficile à ana
```suggestion
- **Lisibilité** : `useState` est très facile à lire lorsque les mises à jour d'état sont simples. Quand ça se complique, elles peuvent gonfler le code de votre composant et le rendre difficile à analyser. Dans ce cas, `useReducer` vous permet de séparer proprement le _comment_ de la logique du _ce qui est arrivé_ des gestionnaires d'événements.
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +- **Débogage** : quand vous avez un bug avec un `useState`, il peut être difficile de dire _où_ l'état a été définit incorrectement et _pourquoi_. Avec un `useReducer`, vous pouvez ajouter des messag
```suggestion
- **Débogage** : quand vous avez un bug avec un `useState`, il peut être difficile de dire _où_ l'état a été mal défini et _pourquoi_. Avec un `useReducer`, vous pouvez ajouter des messages dans la console depuis votre réducteur pour voir chaque mise à jour d'état et _pourquoi_ elles ont lieu (en rapport à quelle `action`). Si chaque `action` est correcte, vous saurez que le problème se trouve dans la logique de réduction elle-même. En revanche, vous devez parcourir plus de code qu'avec `useState`.
```

Attention à ton "définit" qui n'est pas un participe passé, tu fais fréquemment l'erreur (c'est la 3e personne du présent de l'indicatif).

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +- **Tests** : un réducteur est une fonction pure qui ne dépend pas de votre composant. Ça signifie que vous pouvez l'exporter et la tester en isolation. Bien qu'il soit généralement préférable de tes
```suggestion
- **Tests** : un réducteur est une fonction pure qui ne dépend pas de votre composant. Ça signifie que vous pouvez l'exporter et la tester en isolation. Bien qu'il soit généralement préférable de tester des composants dans un environnement plus réaliste, pour une logique de mise à jour d'état plus complexe, il peut être utile de vérifier que votre réducteur renvoie un état spécifique pour un état initial et une action particuliers.
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Nous recommandons d'utiliser un réducteur si vous rencontrez souvent des bugs à cause de mauvaises mises à jour d'état dans certains composants et que vous souhaitez introduire plus de structure dans
```suggestion
Nous recommandons d'utiliser un réducteur si vous rencontrez souvent des bugs à cause de mauvaises mises à jour d'état dans un composant et que vous souhaitez introduire plus de structure dans son code. Vous n'êtes pas obligé·e d'utiliser les réducteurs pour tout : n'hésitez pas à mélanger les approches ! Vous pouvez aussi utiliser `useState` et `useReducer` dans le même composant.
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +- **Les réducteurs doivent être purs**. Tout comme les [fonctions de mise à jour d'état](/learn/queueing-a-series-of-state-updates), les réducteurs sont exécutés pendant le rendu (les actions sont mi
```suggestion
- **Les réducteurs doivent être purs.** Tout comme les [fonctions de mise à jour d'état](/learn/queueing-a-series-of-state-updates), les réducteurs sont exécutés pendant le rendu! ! (Les actions sont mises en attente jusqu'au rendu suivant.) Ça signifie que les réducteurs [doivent être purs](/learn/keeping-components-pure) — les mêmes entrées produisent toujours les mêmes sorties. Ils ne doivent pas envoyer de requêtes, planifier des *timers* ou traiter des effets secondaires (des opérations qui impactent des entités extérieures au composant). Ils doivent mettre à jour des [objets](/learn/updating-objects-in-state) et [des tableaux](/learn/updating-arrays-in-state) en respectant l'immutabilité.
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +- **Chaque action décrit une interaction utilisateur unique, même si ça entraîne plusieurs modifications des données**. Par exemple, si un utilisateur appuie sur le bouton « Réinitialiser » d'un form
```suggestion
- **Chaque action décrit une interaction utilisateur unique, même si ça entraîne plusieurs modifications des données.** Par exemple, si l'utilisateur appuie sur le bouton « Réinitialiser » d'un formulaire comportant cinq champs gérés par un réducteur, il sera plus logique de *dispatcher* une seule action `reset_form` plutôt que cinq actions `set_field` distinctes. Si vous journalisez chaque action d'un réducteur, ce journal doit être suffisamment clair pour vous permettre de reconstruire l'ordre et la nature des interactions et de leurs traitements. Ça facilite le débogage !
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Tout comme [mettre à jour des objets](/learn/updating-objects-in-state#write-concise-update-logic-with-immer) et [des tableaux](/learn/updating-arrays-in-state#write-concise-update-logic-with-immer)
```suggestion
Comme  pour la [mise à jour des objets](/learn/updating-objects-in-state#write-concise-update-logic-with-immer) et [des tableaux](/learn/updating-arrays-in-state#write-concise-update-logic-with-immer) dans un état ordinaire, vous pouvez utiliser la bibliothèque Immer pour rendre les réducteurs plus concis. Ici, [`useImmerReducer`](https://github.com/immerjs/use-immer#useimmerreducer) vous permet de modifier l'état avec un appel à `push` ou encore une affectation `arr[i] =` :
```

2023-07-02 14:53 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +- Utilisez Immer si vous souhaitez écrire des réducteurs avec un style de modification.
```suggestion
- Utilisez Immer si vous souhaitez écrire des réducteurs en modifiant directement l'état entrant.
```

2023-07-02 14:53 UTC, tdd requested changes
Salut @linsolas !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Beau boulot comme d'habitude, même si on sent de-ci de-là la fatigue 😉 et que quelques choix de formulation sont améliorables.

**Il me reste les Défis à revoir**, mais voici déjà la partie principale.

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-04 10:26 UTC, tdd requested changes
Salut @linsolas !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Écoute c'était vraiment bien, tu vois à peine 16 suggestions ou commentaires ! 👏 

J'ai demandé la propagation de certaines modifs que je n'ai pas reprises partout en revanche, je te laisse regarder.

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Remplacez ces deux commentaires `// TODO` avec le code faisant le `dispatch` des actions correspondantes. Pour voir la forme attendue et le type des actions, vérifiez le réducteur dans `messengerRedu
```suggestion
Remplacez ces deux commentaires `// TODO` par du code qui `dispatch` les actions correspondantes. Pour connaître la forme attendue et le type des actions, allez voir le réducteur dans `messengerReducer.js`. Il est déjà écrit, vous n'avez donc pas besoin de le changer. Vous devez seulement *dispatcher* les actions dans `ContactList.js` et `Chat.js`.
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Pour vérifier la forme de l'objet d'action, vous pouvez regarder le réducteur et voir quels champs d'`action` il s'attend à avoir. Par exemple, le cas de l'action `changed_selection` du réducteur res
```suggestion
Pour vérifier la forme de l'objet d'action, vous pouvez examiner le réducteur et voir à quels champs d'`action` il s'attend. Par exemple, le cas de l'action `changed_selection` du réducteur ressemble à ceci :
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Avec le code du réducteur, vous pouvez déduire que les actions doivent ressembler à ceci :
```suggestion
Sur la base du code du réducteur, vous pouvez déduire que les actions doivent ressembler à ceci :
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> -Here is the example updated to dispatch the corresponding messages:
Ben ! Où est la trad ?!

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +1. Afficher une `alert` avec l'email du destinataire et le message.
```suggestion
1. Afficher une `alert` avec l'e-mail du destinataire et le message.
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Ça fonctionne et le champ de saisie se vide quand vous appuyez sur « Envoyer ».
```suggestion
Ça fonctionne et le champ de saisie est vidé quand vous appuyez sur « Envoyer ».
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Le comportement ainsi obtenu est le même. Cependant, gardez à l'esprit que les types d'action doivent idéalement décrire « ce qu'a fait l'utilisateur » plutôt que « la façon dont vous voulez que l'ét
```suggestion
Le comportement visible ne change pas. Cependant, gardez à l'esprit que les types d'action doivent idéalement décrire « ce qu'a fait l'utilisateur » plutôt que « la façon dont vous voulez que l'état change ». Ça facilite l'ajout de fonctionnalités par la suite.
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Avec l'une ou l'autre des solutions, il est important que vous ne placiez *pas* l'`alert` dans un réducteur. Le réducteur doit être une fonction pure — il doit se limiter au calcul du prochain état.
```suggestion
Quelle que soit l'approche retenue, il est important que vous ne placiez *pas* l'`alert` dans un réducteur. Le réducteur doit être une fonction pure : il doit se limiter au calcul du prochain état. Il ne doit rien « faire », y compris afficher des messages à l'utilisateur. Ça doit être fait dans le gestionnaire d'événement (pour détecter ce genre d'erreur, React en mode strict appellera vos réducteurs plusieurs fois. Du coup, si vous placez une alerte dans un réducteur, vous la verrez deux fois).
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +En effet, vous ne souhaitez pas partager un seul brouillon de message entre plusieurs destinataires. Néanmoins, il serait préférable que votre appli « se souvienne » des brouillons pour chaque contac
```suggestion
En effet, vous ne souhaitez pas partager un seul brouillon de message entre plusieurs destinataires. Néanmoins, il serait préférable que votre appli « se souvienne » des brouillons pour chaque contact séparément, et les restaure quand vous changez de contact.
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +La syntaxe `[key]: value` des [propriétés calculées](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Object_initializer#noms_de_propri%C3%A9t%C3%A9s_calcul%C3%A9s) peut vous
```suggestion
La syntaxe `[key]: value` des [noms de propriétés calculés](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Object_initializer#noms_de_propri%C3%A9t%C3%A9s_calcul%C3%A9s) peut vous aider à mettre à jour l'objet `messages` :
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +    0: 'Bonjour, Taylor', // Brouillon pour contactId = 0
Pour info, partout dans les docs on remplace Taylor (Swift) par Clara (Luciani), qu'on a choisie comme "équivalent français" de Taylor Swift en termes de pop culture 😉. Rien de bien grave, mais autant préserver la cohérence !

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Notez que vous n'avez pas eu besoin de modifier les gestionnaires d'événements pour implémenter ce comportement différent. Sans réducteur, vous auriez dû changer chaque gestionnaire d'événement qui m
```suggestion
Notez que vous n'avez pas eu besoin de modifier les gestionnaires d'événements pour implémenter ce nouveau comportement. Sans réducteur, vous auriez dû changer chaque gestionnaire d'événement qui met à jour l'état.
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Voici une esquisse plus détaillée de l'implémentation :
Ah ah, pas mal "esquisse" 😁

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +Souvenez-vous qu'une fonction de réduction prend deux arguments — l'état courant et l'objet d'action — et renvoie le prochain état. Que doit-en faire votre implémentation de `dispatch` ?
```suggestion
Souvenez-vous qu'une fonction de réduction prend deux arguments — l'état courant et l'objet d'action — et renvoie le prochain état. Que doit en faire votre implémentation de `dispatch` ?
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +*Dispatcher* une action appelle un réducteur avec l'état actuel et l'action, puis conserve le résultat comme le prochain état. Voici à quoi ça ressemble dans le code :
```suggestion
*Dispatcher* une action appelle un réducteur avec l'état actuel et l'action, puis conserve le résultat comme prochain état. Voici à quoi ça ressemble dans le code :
```

2023-07-04 10:26 UTC, tdd commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +En effet, les actions *dispatchées* sont mises en attente jusqu'au prochain rendu, [à l'image des fonctions de mise à jour](/learn/queueing-a-series-of-state-updates).
```suggestion
En effet, les actions *dispatchées* sont mises en file d'attente jusqu'au prochain rendu, [tout comme les fonctions de mise à jour](/learn/queueing-a-series-of-state-updates).
```

2023-07-06 08:10 UTC, tdd commented
Coucou @linsolas si tu peux trouver un peu de temps pour traiter ma review dans les prochains jours ce serait top 😗

2023-07-06 17:21 UTC, linsolas commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> +    0: 'Bonjour, Taylor', // Brouillon pour contactId = 0
OK, ça me va, ma fille s'appelle Clara 😉

2023-07-06 17:21 UTC, linsolas commented on src/content/learn/extracting-state-logic-into-a-reducer.md
> -Here is the example updated to dispatch the corresponding messages:
Je vais les remettre. J'avais fait une fausse manipulation dans l'IDE, plusieurs lignes avaient été perdues. Je pensais les avoir remises, mais j'en ai visiblement oublié 2...

2023-07-06 17:40 UTC, linsolas commented
Hello @tdd ,

Je viens de mettre à jour la PR avec toutes tes remarques, les 2 lignes oubliées ont été remises en état.

2023-07-07 08:47 UTC, tdd approved these changes

2023-07-07 08:47 UTC, merged

2023-07-07 08:49 UTC, tdd commented
Et voilà, mergé ! Du coup @linsolas souhaites-tu toujours embrayer sur "Scaling up with reducer…" ?

Si tu veux dédier du temps ensuite, je te voyais bien prendre des pages associées au fil du temps, notamment :

- useContext (car beaucoup de recoupements / clonages de contenus, dont homogénéité souhaitable)
- useReducer (idem)
- Pourquoi pas les deux pages restantes de la partie Managing State ? (Sinon je les prendrai)

Qu'en penses-tu ?

2023-07-07 08:53 UTC, linsolas commented
Hello @tdd,

Alors pour "Scaling up...", j'ai fini la traduction hier 😃 Je dois encore me faire ma propre relecture, donc normalement la PR sera là en début de semaine prochaine au plus tard.

Quant aux autres pages, je suis partant mais je pars en congés d'ici 2 semaines, donc je te dis très vite ce que je pense pouvoir faire d'ici là.