Translation of the "useDebugValue" page from API references
reactjs/fr.react.dev pull request #507
Opened 2023-07-05 14:33 UTC by MatteoGauthier

Hello 👋 ! Voici une petite PR pour la traduction de la page reference/react/useDebugValue de la documentation.

Merci encore aux maintainers pour leurs travail 🙏

2023-07-05 14:36 UTC, tdd commented
Heeeey mec j'y croyais plus, demain je l'aurais faite moi-même en fait ! 😉 

Je te reviewe ça cette semaine.

2023-07-05 15:02 UTC, tdd requested changes
Salut @MatteoGauthier !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Bon les deux principaux points sont :

- On traduit "outils de développement React" partout (cf. nav etc.)
- On évite "cela" au profit de "ça"

Je te laisse regarder le reste.

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-06 12:25 UTC, MatteoGauthier commented
Salut @tdd merci pour ta review, je viens de commit tes RCs. Concernant la traduction de "React Devtools", je me suis inspiré de la section [Autres Hooks](https://fr.react.dev/reference/react#other-hooks) de la page Hooks fournis par React. Est-ce que tu veux que je fasse la modif sur le fichier Markdown correspondant ?
https://github.com/reactjs/fr.react.dev/blob/f5263a23496c365c8057db3f628ae00c5d1a5fa2/src/content/reference/react/index.md?plain=1#L114

Bonne journée à toi !

2023-07-06 14:31 UTC, tdd commented
@MatteoGauthier bonne remarque ; t'embête pas, je vais l'ajouter à ma passe de revue visuelle finale.

2023-07-06 14:40 UTC, merged