Scaling up with reducer and context
reactjs/fr.react.dev pull request #511
Opened 2023-07-07 20:59 UTC by linsolas

Traduction de la page https://react.dev/learn/scaling-up-with-reducer-and-context

2023-07-10 10:31 UTC, tdd requested changes
Salut @linsolas !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Écoute c'est super bravo, j'ai très peu de choses à dire.

Pour le choix câblage / plomberie, je te laisse faire l'arbitrage final si tu ne me rejoins pas (attention à bien être cohérent sur l'ensemble).

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-10 10:31 UTC, tdd commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +## Déplacer tout le câblage dans un seul fichier {/*moving-all-wiring-into-a-single-file*/}
```suggestion
## Déplacer toute cette plomberie dans un seul fichier {/*moving-all-wiring-into-a-single-file*/}
```

On parle davantage de "plomberie" que de câblage pour ce genre de choses, me semble-t-il. Même s'il est vrai qu'ici Dan a parlé de "wiring" plutôt que de "plumbing", mais je trouve que "câblage" est plus rare en VF.

2023-07-10 10:31 UTC, tdd commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +Vous n'êtes pas obligé de le faire, mais vous pouvez encore alléger les composants en déplaçant le réducteur et le contexte dans un seul fichier. Pour le moment, `TasksContext.js` ne contient que les
```suggestion
Vous n'êtes pas obligé·e de le faire, mais vous pouvez encore alléger les composants en déplaçant le réducteur et le contexte dans un seul fichier. Pour le moment, `TasksContext.js` ne contient que les deux déclarations de contexte :
```

2023-07-10 10:31 UTC, tdd commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +**Ça supprime toute la complexité et le câblage de votre composant `TaskApp` :**
```suggestion
**Ça supprime toute la complexité et la plomberie de votre composant `TaskApp` :**
```

2023-07-10 10:31 UTC, tdd commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +Quand un composant a besoin de lire le contexte, il peut le faire depuis ces fonctions :
```suggestion
Quand un composant a besoin de lire le contexte, il peut le faire *via* ces fonctions :
```

2023-07-10 10:31 UTC, tdd commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +Ça ne change en rien le comportement, mais ça vous laisse l'opportunité de diviser davantage ces contextes ou d'ajouter de la logique à ces fonctions. **Tout le câblage du contexte et du réducteur se
```suggestion
Ça ne change en rien le comportement, mais ça vous laisse l'opportunité de diviser davantage ces contextes ou d'ajouter de la logique à ces fonctions. **Toute la plomberie du contexte et du réducteur se trouvent désormais dans `TasksContext.js`. Ça laisse les composants propres et épurés, et ils peuvent ainsi se concentrer sur ce qu'ils doivent afficher plutôt que savoir où chercher les données :**
```

2023-07-10 10:31 UTC, tdd commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +Vous pouvez voir le `TasksProvider` comme une partie de l'écran qui sait comment traiter les tâches, `useTasks` comme une façon de les lire et `useTasksDispatch` comme un moyen de les mettre à jour à
```suggestion
Vous pouvez voir le `TasksProvider` comme une partie de l'écran qui sait comment traiter les tâches, `useTasks` comme une façon de les lire et `useTasksDispatch` comme un moyen de les mettre à jour à partir de n'importe quel composant plus bas dans l'arbre.
```

2023-07-10 10:31 UTC, tdd commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +Les fonctions comme `useTasks` et `useTasksDispatch` sont appelées *[Hooks personnalisés](/learn/reusing-logic-with-custom-hooks)*. Votre fonction est considérée comme un Hook personnalisé si son nom
```suggestion
Les fonctions comme `useTasks` et `useTasksDispatch` sont ce qu'on appelle des *[Hooks personnalisés](/learn/reusing-logic-with-custom-hooks)*. Votre fonction est considérée comme un Hook personnalisé si son nom commence par `use`. Vous pouvez alors utiliser d'autres Hooks comme `useContext` à l'intérieur.
```

2023-07-10 10:31 UTC, tdd commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +Au fur et à mesure que votre appli grandit, il se peut que vous ayez de nombreuses paires contexte-réducteur telle que celle-ci. C'est un moyen puissant de mettre votre appli à l'échelle et [d'élever
```suggestion
Au fur et à mesure que votre appli grandit, il se peut que vous ayez de nombreuses paires contexte-réducteur comme celle-ci. C'est un moyen puissant de faire grandir votre appli et de [faire remonter l'état](/learn/sharing-state-between-components) sans trop d'efforts chaque fois que vous avez besoin d'accéder aux données au plus profond de l'arbre.
```

2023-07-10 10:31 UTC, tdd commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +- Vous pouvez combiner le réducteur avec le contexte pour permettre à n'importe quel composant de lire et mettre à jour l'état qui se trouve au dessus de lui.
```suggestion
- Vous pouvez combiner le réducteur avec le contexte pour permettre à n'importe quel composant de lire et mettre à jour l'état qui se trouve au-dessus de lui.
```

2023-07-10 14:51 UTC, linsolas commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +## Déplacer tout le câblage dans un seul fichier {/*moving-all-wiring-into-a-single-file*/}
Pas de soucis, je parle souvent moi-même de plomberie quand il s'agit de ce type de choses, j'étais juste resté sur une traduction plus littérale.

2023-07-10 14:54 UTC, linsolas commented on src/content/learn/scaling-up-with-reducer-and-context.md
> +  { id: 0, text: 'Le chemin du philosophe', done: true },
Fait !

2023-07-11 07:53 UTC, tdd approved these changes

2023-07-11 09:13 UTC, merged