Translation of the “Updating Arrays in State” page
reactjs/fr.react.dev pull request #542
Opened 2023-07-22 16:00 UTC by LaureRC

Traduction française de la page [Updating Arrays in State](https://react.dev/learn/updating-arrays-in-state).

2023-07-22 16:16 UTC, tdd commented
@LaureRC tu as des trads de référence ailleurs dans la Doc pour ces mêmes exemples de code, notamment sur l'accueil de la section

2023-07-22 16:28 UTC, LaureRC commented
> @LaureRC tu as des trads de référence ailleurs dans la Doc pour ces mêmes exemples de code, notamment sur l'accueil de la section

Oh bien vu! J'avais consulté cette page pour la partie Introduction et pour le titre par exemple, mais je n'avais pas vu la partie sur ce fameux bout de code avec "Art Bucket list" qui m'a posé problème 😄 merci!

2023-07-25 19:13 UTC, tdd requested changes
Salut @LaureRC !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Écoute c'est plutôt très bien ; j'ai revu jusqu'aux Défis pour le moment, je te laisse traiter ça (y'a une modif à annuler sur de la trad de littéral technique, et l'annulation est à reporter sur le code qui suit sans que je l'ai fait moi-même, gaffe).

Je te finalise la revue ASAP, je suis en congés familiaux là…

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +Cependant, **même si vous copiez un tableau, vous ne pouvez pas modifier directement les éléments existants _à l'intérieur_ de celui-ci.** C'est parce que la copie est superficielle : le nouveau tabl
```suggestion
Cependant, **même si vous copiez un tableau, vous ne pouvez pas modifier directement les éléments existants _à l'intérieur_ de celui-ci.** C'est parce que la copie est superficielle : le nouveau tableau contiendra les mêmes éléments que le tableau d'origine. Ainsi, si vous modifiez un objet à l'intérieur du tableau copié, vous modifiez l'état existant. Par exemple, le code suivant est problématique.
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +Dans cet exemple, deux listes d'œuvres d'art séparées ont le même état initial. Elles sont censées être isolées, mais à cause d'une mutation, leur état est accidentellement partagé, et cocher une cas
```suggestion
Dans cet exemple, deux listes d'œuvres d'art séparées ont le même état initial. Elles sont censées être isolées, mais à cause d'une modification directe, leur état est accidentellement partagé, et cocher une case dans l'une des listes affecte l'autre liste :
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +Le problème se trouve dans un code comme celui-ci :
```suggestion
Le problème se trouve dans du code comme celui-ci :
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +    // Créez un *nouvel* objet avec les modifications
```suggestion
    // Crée un *nouvel* objet avec les modifications
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +Ici, `...` est la syntaxe de *spread* d'objets utilisée pour [créer une copie d'un objet.](/learn/updating-objects-in-state#copying-objects-with-the-spread-syntax)
```suggestion
Ici, `...` est la syntaxe de *spread* d'objets utilisée pour [créer une copie d'un objet](/learn/updating-objects-in-state#copying-objects-with-the-spread-syntax).
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +Avec cette approche, aucun des éléments de l'état n'est modifié et le bug est corrigé :
```suggestion
Avec cette approche, aucun des éléments de l'état existant n'est modifié et le bug est corrigé :
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +        // Créez un *nouvel* objet avec les modifications
```suggestion
        // Crée un *nouvel* objet avec les modifications
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +        // Créez un *nouvel* objet avec les modifications
```suggestion
        // Crée un *nouvel* objet avec les modifications
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +En général, **vous ne devriez modifier que les objets que vous venez de créer.** Si vous insérez une *nouvelle* œuvre d'art, vous pouvez la modifier, mais si vous traitez quelque chose qui est déjà d
```suggestion
En général, **vous ne devriez modifier que les objets que vous venez de créer**. Si vous insérez une *nouvelle* œuvre d'art, vous pouvez la modifier, mais si vous traitez quelque chose qui est déjà dans l'état, vous devez faire une copie.
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +Mettre à jour des tableaux imbriqués sans mutation peut conduire à du code un peu répétitif. [Tout comme avec les objets](/learn/updating-objects-in-state#write-concise-update-logic-with-immer):
```suggestion
Mettre à jour des tableaux imbriqués sans modification directe peut conduire à du code un peu répétitif. [Tout comme avec les objets](/learn/updating-objects-in-state#write-concise-update-logic-with-immer) :
```

2023-07-25 19:13 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +En interne, Immer construit toujours le prochain état à partir de zéro en fonction des changements que vous avez apportés au `draft`. Cela permet de maintenir vos gestionnaires d'événements très conc
```suggestion
En interne, Immer construit toujours le prochain état à partir de zéro en fonction des changements que vous avez apportés au `draft`. Ça permet de garder des gestionnaires d'événements très concis sans jamais modifier l'état directement.
```

2023-07-25 19:13 UTC, tdd requested changes
Salut @LaureRC !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

Écoute c'est plutôt très bien ; j'ai revu jusqu'aux Défis pour le moment, je te laisse traiter ça (y'a une modif à annuler sur de la trad de littéral technique, et l'annulation est à reporter sur le code qui suit sans que je l'ai fait moi-même, gaffe).

Je te finalise la revue ASAP, je suis en congés familiaux là…

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-07-25 20:12 UTC, LaureRC commented
> Salut @LaureRC !
> 
> Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.
> 
> Écoute c'est plutôt très bien ; j'ai revu jusqu'aux Défis pour le moment, je te laisse traiter ça (y'a une modif à annuler sur de la trad de littéral technique, et l'annulation est à reporter sur le code qui suit sans que je l'ai fait moi-même, gaffe).
> 
> Je te finalise la revue ASAP, je suis en congés familiaux là…
> 
> **Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**
> 
> Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**
> 
> Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝
> 
> Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.
> 
> Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

Hello @tdd!

Merci pour cette review, j'ai ajouté un commit qui groupe tes retours et un autre pour mettre à jour du code pour suivre un de tes commentaires. 

Concernant "mutation" je pensais qu'il pouvait être gardé (je l'avais beaucoup utilisé dans la traduction de la page "Updating objects in State") mais je pense avoir saisi la nuance, c'est bien noté pour les prochaines fois! 

Pour `toSpliced` et `with` je ne connaissais pas leur existence alors merci de l'info, ça va m'être utile!

Et pas de problème pour la review, prends ton temps, je n'ai pas de congés en Août donc profite de tes congés il n'y a pas d'urgence! :)

2023-07-26 07:49 UTC, tdd approved these changes

2023-07-26 13:04 UTC, tdd requested changes
Coucou @LaureRC ! Voici la fin de ma review. Bizarre comme tout à coup tu ne mettais plus d'insécable devant les deux-points…

2023-07-26 13:04 UTC, tdd commented on src/content/learn/updating-arrays-in-state.md
> +Avec Immer, vous pouvez écrire du code de manière modifiante, tant que vous ne modifiez que les parties du `draft` que Immer vous fournit. Ici, toutes les mutations sont effectuées sur le `draft` de
```suggestion
Avec Immer, vous pouvez écrire du code de manière modifiante, tant que vous ne modifiez que des parties du `draft` que Immer vous fournit. Ici, toutes les modifications sont effectuées sur le `draft` de sorte que le code fonctionne correctement :
```

2023-08-01 09:26 UTC, tdd approved these changes

2023-08-01 09:29 UTC, merged