Translation of "<textarea>" page
reactjs/fr.react.dev pull request #551
Opened 2023-08-15 11:02 UTC by nina-alin

Bonjour ! 

Voici ma PR pour `<textarea>`. J'espère m'être améliorée sur celle-ci ! :)

2023-08-17 07:24 UTC, tdd requested changes
Salut @nina-alin !

Avant toute chose, **merci pour tout ce boulot !** C'est super cool de nous filer un coup de main.

L'essentiel des *tweaks* se concentre sur quelques points :

- pas de majuscule après un deux-points
- La plupart des usages de "render" se traduisent pas "afficher", voire "produire" selon le cas, mais rarement "faire le rendu", qu'on utilise que lorsque le texte parle de la phase technique de rendu (genre page "Rendu et Commit"), car c'est ampoulé
- "Ça" plutôt que "Cela"
- On traduit juste après les textes d'erreurs / warnings / console laissés intentionnellement en VO dans leur 1ère apparition (bloc de console, titre de section).

Sinon trop cool ! 👍 

**Avant de traiter les retours, lis bien TOUT ce message, notamment les consignes d'intégration optimale des retours par lot(s)**

Tout est fait sous forme de Suggestions GitHub, il te suffit à chaque suggestion que tu approuves de 
cliquer le bouton **d'ajout au lot de modifs à committer** (**pas** de commit direct !), et sur la fin de créer le commit groupé. **(ce mode de regroupement en un seul commit est à favoriser absolument, mais tu devras aller dans l'onglet _Files changed_ pour y accéder, il n'est pas utilisable dans l’onglet _Conversation_)**

Si certaines appellent discussion, n'hésite pas, tu réponds, on en parle, on avance ensemble 🤝 

Quand tout sera bouclé côté code, je ferai une repasse visuelle finale en local avant de fusionner. J'y recalerai si besoin les _usual suspects_ : espaces insécables avant les ponctuations doubles, et apostrophes françaises.

Encore mille mercis, j'ai hâte de voir cette PR finalisée et dans `main` !

2023-08-17 07:24 UTC, tdd commented on src/content/reference/react-dom/components/textarea.md
> +Pour corriger votre code, mettez à jour de manière synchrone `e.target.value` :
```suggestion
Pour corriger votre code, mettez à jour de manière synchrone avec `e.target.value` :
```

2023-08-17 07:24 UTC, tdd commented on src/content/reference/react-dom/components/textarea.md
> +  // 🔴 Bug : mettre à jour un champ de saisie avec autre chose que e.target.value
https://github.com/reactjs/react.dev/issues/6237

2023-08-17 07:24 UTC, tdd commented on src/content/reference/react-dom/components/textarea.md
> +Si cela ne corrige pas le problème, il est possible que la zone de texte soit supprimée et réinsérée dans le DOM à chaque frappe. Cela peut se produire si vous [réinitialisez accidentellement](/learn
```suggestion
Si ça ne corrige pas le problème, il est possible que la zone de texte soit supprimée et réinsérée dans le DOM à chaque frappe. Ça peut se produire si vous [réinitialisez accidentellement l'état](/learn/preserving-and-resetting-state) à chaque nouveau rendu. Par exemple, ça peut se produire si la zone de texte ou l'un de ses parents reçoit toujours un attribut `key` différent, ou si vous imbriquez des définitions de composants (ce qui n'est pas autorisé en React et provoque le remontage du composant « interne » à chaque rendu).
```

2023-08-17 07:24 UTC, tdd commented on src/content/reference/react-dom/components/textarea.md
> +Si vous passez une `value` à un composant, il doit rester une chaîne de caractères tout au long de son cycle de vie.
```suggestion
_(« Un composant passe un champ non contrôlé en mode contrôlé », NdT)_

Si vous passez une `value` à un composant, celle-ci doit être une chaîne de caractères tout au long de son cycle de vie.
```

2023-08-17 07:24 UTC, tdd commented on src/content/reference/react-dom/components/textarea.md
> +Si vous passez `value={undefined}` à un composant, puis plus tard `value="quelqueChose"`, React ne saura pas si vous voulez que le composant soit contrôlé ou non. Un composant contrôlé doit toujours
```suggestion
Si vous passez `value={undefined}` à un composant, puis plus tard `value="quelqueChose"`, React ne saura pas si vous voulez que le composant soit contrôlé ou non. Un composant contrôlé doit toujours recevoir une chaîne de caractères en `value`, pas `null` ni `undefined`.
```

2023-08-21 08:37 UTC, nina-alin commented on src/content/reference/react-dom/components/textarea.md
> +  // 🔴 Bug : mettre à jour un champ de saisie avec autre chose que e.target.value
C'est bien, ces traductions permettent aussi de corriger la documentation originale 👍 

Je ne sais pas si c'est une "convention" qu'ils essayent de mettre en place ou si c'est une erreur d'écriture.

2023-08-21 08:39 UTC, nina-alin commented on src/content/reference/react-dom/components/textarea.md
> +Si votre `value` provient d'une API (_interface de programmation d'application, NdT_) ou d'une variable d'état, elle peut être initialisée à `null` ou `undefined`. Dans ce cas, définissez-la avec une
Pourquoi avoir enlevé la NdT ? API étant un terme anglophone, je trouvais judicieux de le préciser.

2023-08-21 08:41 UTC, tdd commented on src/content/reference/react-dom/components/textarea.md
> +Si votre `value` provient d'une API (_interface de programmation d'application, NdT_) ou d'une variable d'état, elle peut être initialisée à `null` ou `undefined`. Dans ce cas, définissez-la avec une
Terme largement assez courant pour notre auditoire cible. On ne détaille que les acronymes spécifiques à React (ex. RDT) ou inhabituels, sinon ça fait trop de bruit.

2023-08-21 08:47 UTC, nina-alin commented
Hello ! @tdd 

J'ai bien reporté toutes les modifications, en plus d'un commit pour le problème des majuscules après les deux points. 

Merci encore de prendre tout ce temps pour nous apprendre à traduire les pages ! C'est un travail monstre que tu fournis ! 

Bonne journée à toi !

2023-08-21 08:59 UTC, merged